Repository ec-europa/ecl-twig, pull requests merged in 2019-02, with the labels that each got.

#17 feat: EC component Tag
  src/ec/packages/ec-component-tag/.npmignore
  src/ec/packages/ec-component-tag/README.md
  src/ec/packages/ec-component-tag/__snapshots__/tag.test.js.snap
  src/ec/packages/ec-component-tag/docs/tag.md
  src/ec/packages/ec-component-tag/package.json
  src/ec/packages/ec-component-tag/tag.html.twig
  src/ec/packages/ec-component-tag/tag.story.js
  src/ec/packages/ec-component-tag/tag.test.js
Labels: pr: review needed

#16 feat: EC component Link
  src/ec/packages/ec-component-link/.npmignore
  src/ec/packages/ec-component-link/README.md
  src/ec/packages/ec-component-link/__snapshots__/link.test.js.snap
  src/ec/packages/ec-component-link/docs/link.md
  src/ec/packages/ec-component-link/link.html.twig
  src/ec/packages/ec-component-link/link.story.js
  src/ec/packages/ec-component-link/link.test.js
  src/ec/packages/ec-component-link/package.json
  yarn.lock
Labels: pr: review needed

#14 feat: EU component Button
  src/eu/packages/eu-component-button/.npmignore
  src/eu/packages/eu-component-button/README.md
  src/eu/packages/eu-component-button/__snapshots__/button.test.js.snap
  src/eu/packages/eu-component-button/button.html.twig
  src/eu/packages/eu-component-button/button.story.js
  src/eu/packages/eu-component-button/button.test.js
  src/eu/packages/eu-component-button/docs/cta.md
  src/eu/packages/eu-component-button/docs/ghost.md
  src/eu/packages/eu-component-button/docs/primary.md
  src/eu/packages/eu-component-button/docs/search.md
  src/eu/packages/eu-component-button/docs/secondary.md
  src/eu/packages/eu-component-button/package.json
Labels: pr: review needed

#24 chore(ci): test yarn.lock
  .drone.yml
  .eslintrc.js
  package.json
  scripts/check-lockfile.sh
  src/ec/packages/ec-component-link/__snapshots__/link.test.js.snap
  src/ec/packages/ec-component-tag/__snapshots__/tag.test.js.snap
  yarn.lock
Labels: pr: under review

#31 feat: EU component Link
  src/eu/packages/eu-component-link/.npmignore
  src/eu/packages/eu-component-link/README.md
  src/eu/packages/eu-component-link/__snapshots__/link.test.js.snap
  src/eu/packages/eu-component-link/docs/link.md
  src/eu/packages/eu-component-link/link.html.twig
  src/eu/packages/eu-component-link/link.story.js
  src/eu/packages/eu-component-link/link.test.js
  src/eu/packages/eu-component-link/package.json
  yarn.lock
Labels: pr: review needed

#33 feat: Ec component site header
  src/ec/packages/ec-component-search-form/search-form.html.twig
  src/ec/packages/ec-component-site-header/README.md
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
  src/ec/packages/ec-component-site-header/docs/site-header.md
  src/ec/packages/ec-component-site-header/package.json
  src/ec/packages/ec-component-site-header/site-header.html.twig
  src/ec/packages/ec-component-site-header/site-header.story.js
  src/ec/packages/ec-component-site-header/site-header.test.js
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: under review

#41 feat(ec-breadcrumb): implement JS code
  .eslintrc.js
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-breadcrumb/breadcrumb.story.js
  src/eu/.storybook/preview-head.html
  utils/storybook-addon-code/src/index.js
Labels: pr: under review

#40 fix: footer icons and data
  src/ec/packages/ec-component-footer/README.md
  src/ec/packages/ec-component-footer/__snapshots__/footer.test.js.snap
  src/ec/packages/ec-component-footer/demo/data.js
  src/ec/packages/ec-component-footer/docs/footer.md
  src/ec/packages/ec-component-footer/footer.story.js
  src/ec/packages/ec-component-footer/package.json
  yarn.lock
Labels: pr: review needed

#38 feat: Add social-media-share component
  src/ec/packages/ec-component-social-media-share/.npmignore
  src/ec/packages/ec-component-social-media-share/README.md
  src/ec/packages/ec-component-social-media-share/__snapshots__/social-media-share.test.js.snap
  src/ec/packages/ec-component-social-media-share/demo/data.js
  src/ec/packages/ec-component-social-media-share/docs/social-media-share.md
  src/ec/packages/ec-component-social-media-share/package.json
  src/ec/packages/ec-component-social-media-share/social-media-share.html.twig
  src/ec/packages/ec-component-social-media-share/social-media-share.story.js
  src/ec/packages/ec-component-social-media-share/social-media-share.test.js
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: modification needed

#36 feat: Add social-media-follow component
  src/ec/packages/ec-component-social-media-follow/.npmignore
  src/ec/packages/ec-component-social-media-follow/README.md
  src/ec/packages/ec-component-social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/ec/packages/ec-component-social-media-follow/demo/data.js
  src/ec/packages/ec-component-social-media-follow/docs/social-media-follow.md
  src/ec/packages/ec-component-social-media-follow/package.json
  src/ec/packages/ec-component-social-media-follow/social-media-follow.html.twig
  src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js
  src/ec/packages/ec-component-social-media-follow/social-media-follow.test.js
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: modification needed
