Repository ec-europa/ecl-twig, pull requests merged in 2019-09, with the labels that each got.

#119 feat(menu-legacy): menu-legacy twig implementation - TWIG-5
  src/ec/packages/ec-component-menu-legacy/.npmignore
  src/ec/packages/ec-component-menu-legacy/CHANGELOG.md
  src/ec/packages/ec-component-menu-legacy/README.md
  src/ec/packages/ec-component-menu-legacy/__snapshots__/menu-legacy.test.js.snap
  src/ec/packages/ec-component-menu-legacy/demo/data.js
  src/ec/packages/ec-component-menu-legacy/docs/menu-legacy.md
  src/ec/packages/ec-component-menu-legacy/menu-legacy.html.twig
  src/ec/packages/ec-component-menu-legacy/menu-legacy.story.js
  src/ec/packages/ec-component-menu-legacy/menu-legacy.test.js
  src/ec/packages/ec-component-menu-legacy/package.json
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: review needed

#118 feat(skip-link): skip-link implementation - TWIG-18
  src/ec/packages/ec-component-skip-link/.npmignore
  src/ec/packages/ec-component-skip-link/CHANGELOG.md
  src/ec/packages/ec-component-skip-link/README.md
  src/ec/packages/ec-component-skip-link/__snapshots__/skip-link.test.js.snap
  src/ec/packages/ec-component-skip-link/docs/skip-link.md
  src/ec/packages/ec-component-skip-link/package.json
  src/ec/packages/ec-component-skip-link/skip-link.html.twig
  src/ec/packages/ec-component-skip-link/skip-link.story.js
  src/ec/packages/ec-component-skip-link/skip-link.test.js
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: review needed

#143 feat(menu-legacy): 2.9.1 - Fixing twig template - Twig 44
  src/ec/packages/ec-component-icon/docs/icon.md
  src/ec/packages/ec-component-menu-legacy/__snapshots__/menu-legacy.test.js.snap
  src/ec/packages/ec-component-menu-legacy/demo/data.js
  src/ec/packages/ec-component-menu-legacy/docs/menu-legacy.md
  src/ec/packages/ec-component-menu-legacy/menu-legacy.html.twig
  src/ec/packages/ec-component-menu-legacy/menu-legacy.story.js
  src/ec/packages/ec-component-menu-legacy/menu-legacy.test.js
Labels: pr: review needed

#142 feat: (table) - 2.9.1 - Addding package in the list of components - TWIG-43
  src/ec/packages/ec-components/package.json
Labels: pr: review needed

#138 fix(media-container): refactor markup - TWIG-42
  src/ec/packages/ec-component-media-container/__snapshots__/media-container.test.js.snap
  src/ec/packages/ec-component-media-container/media-container.html.twig
Labels: pr: under review

#136 fix(card): refactor markup and use aria-label instead of alt - TWIG 33
  src/ec/packages/ec-component-card/__snapshots__/card.test.js.snap
  src/ec/packages/ec-component-card/card.html.twig
Labels: pr: under review

#141 fix(text-input): update style of text inputs - TWIG-38
  src/ec/packages/ec-component-search-form/__snapshots__/search-form.test.js.snap
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
  src/ec/packages/ec-component-text-input/__snapshots__/text-input.test.js.snap
  src/ec/packages/ec-component-text-input/docs/text-input.md
  src/ec/packages/ec-component-text-input/text-input.html.twig
  src/ec/packages/ec-component-text-input/text-input.story.js
Labels: pr: under review

#132 feat(checkbox): add component - TWIG-9
  src/ec/packages/ec-component-checkbox/.npmignore
  src/ec/packages/ec-component-checkbox/CHANGELOG.md
  src/ec/packages/ec-component-checkbox/README.md
  src/ec/packages/ec-component-checkbox/__snapshots__/checkbox.test.js.snap
  src/ec/packages/ec-component-checkbox/checkbox-button.html.twig
  src/ec/packages/ec-component-checkbox/checkbox-group.html.twig
  src/ec/packages/ec-component-checkbox/checkbox.story.js
  src/ec/packages/ec-component-checkbox/checkbox.test.js
  src/ec/packages/ec-component-checkbox/demo/data.js
  src/ec/packages/ec-component-checkbox/package.json
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: under review

#135 fix(radio): Update component markup - TWIG-36
  src/ec/packages/ec-component-radio/README.md
  src/ec/packages/ec-component-radio/__snapshots__/radio.test.js.snap
  src/ec/packages/ec-component-radio/demo/data.js
  src/ec/packages/ec-component-radio/package.json
  src/ec/packages/ec-component-radio/radio-button.html.twig
  src/ec/packages/ec-component-radio/radio-group.html.twig
  src/ec/packages/ec-component-radio/radio.story.js
  src/ec/packages/ec-components/package.json
Labels: pr: review needed

#146 chore: use ECL 2.11.0 legacy presets - TWIG-46
  src/ec/.storybook/preview-head.html
Labels: pr: review needed

#147 fix(select): update style of select - TWIG-37
  src/ec/packages/ec-component-select/__snapshots__/select.test.js.snap
  src/ec/packages/ec-component-select/docs/select.md
  src/ec/packages/ec-component-select/select.html.twig
  src/ec/packages/ec-component-select/select.story.js
Labels: pr: modification needed

#133 feat(date-block): Adding component - TWIG-31
  src/ec/packages/ec-component-date-block/.npmignore
  src/ec/packages/ec-component-date-block/CHANGELOG.md
  src/ec/packages/ec-component-date-block/README.md
  src/ec/packages/ec-component-date-block/__snapshots__/date-block.test.js.snap
  src/ec/packages/ec-component-date-block/date-block.html.twig
  src/ec/packages/ec-component-date-block/date-block.story.js
  src/ec/packages/ec-component-date-block/date-block.test.js
  src/ec/packages/ec-component-date-block/demo/data.js
  src/ec/packages/ec-component-date-block/docs/date-block.md
  src/ec/packages/ec-component-date-block/package.json
  yarn.lock
Labels: pr: under review

#150 feat(text-input): adding extra classes for label, renaming prop TWIG-52
  src/ec/packages/ec-component-search-form/search-form.html.twig
  src/ec/packages/ec-component-search-form/search-form.story.js
  src/ec/packages/ec-component-text-area/docs/text-area.md
  src/ec/packages/ec-component-text-area/text-area.html.twig
  src/ec/packages/ec-component-text-area/text-area.test.js
  src/ec/packages/ec-component-text-input/__snapshots__/text-input.test.js.snap
  src/ec/packages/ec-component-text-input/docs/text-input.md
  src/ec/packages/ec-component-text-input/text-input.html.twig
  src/ec/packages/ec-component-text-input/text-input.test.js
Labels: pr: under review

#129 chore: twig-2.11.0 - Updating backward compatible libraries
  package.json
  yarn.lock
Labels: pr: under review

#134 feat(file-upload): file-upload twig implementation - TWIG-30
  src/ec/packages/ec-component-file-upload/.npmignore
  src/ec/packages/ec-component-file-upload/CHANGELOG.md
  src/ec/packages/ec-component-file-upload/README.md
  src/ec/packages/ec-component-file-upload/__snapshots__/file-upload.test.js.snap
  src/ec/packages/ec-component-file-upload/demo/data.js
  src/ec/packages/ec-component-file-upload/file-upload.html.twig
  src/ec/packages/ec-component-file-upload/file-upload.story.js
  src/ec/packages/ec-component-file-upload/file-upload.test.js
  src/ec/packages/ec-component-file-upload/package.json
  yarn.lock
Labels: pr: review needed

#139 feat(description-list): horizontal variant - TWIG-39
  src/ec/packages/ec-component-description-list/README.md
  src/ec/packages/ec-component-description-list/__snapshots__/description-list.test.js.snap
  src/ec/packages/ec-component-description-list/description-list.html.twig
  src/ec/packages/ec-component-description-list/description-list.story.js
  src/ec/packages/ec-component-description-list/description-list.test.js
  src/ec/packages/ec-component-description-list/package.json
  yarn.lock
Labels: pr: review needed

#149 feat(dropdown-legacy): Adding component - TWIG-3
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-dropdown-legacy/.npmignore
  src/ec/packages/ec-component-dropdown-legacy/CHANGELOG.md
  src/ec/packages/ec-component-dropdown-legacy/README.md
  src/ec/packages/ec-component-dropdown-legacy/__snapshots__/dropdown-legacy.test.js.snap
  src/ec/packages/ec-component-dropdown-legacy/demo/data.js
  src/ec/packages/ec-component-dropdown-legacy/docs/dropdown-legacy.md
  src/ec/packages/ec-component-dropdown-legacy/dropdown-legacy.html.twig
  src/ec/packages/ec-component-dropdown-legacy/dropdown-legacy.story.js
  src/ec/packages/ec-component-dropdown-legacy/dropdown-legacy.test.js
  src/ec/packages/ec-component-dropdown-legacy/package.json
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: under review

#151 fix(site-header): Bridge language selector and overlay - TWIG-40
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-accordion/__snapshots__/accordion.test.js.snap
  src/ec/packages/ec-component-button/__snapshots__/button.test.js.snap
  src/ec/packages/ec-component-button/button.html.twig
  src/ec/packages/ec-component-contextual-navigation/__snapshots__/contextual-navigation.test.js.snap
  src/ec/packages/ec-component-dropdown-legacy/__snapshots__/dropdown-legacy.test.js.snap
  src/ec/packages/ec-component-expandable/__snapshots__/expandable.test.js.snap
  src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
  src/ec/packages/ec-component-gallery/__snapshots__/gallery.test.js.snap
  src/ec/packages/ec-component-language-list/__snapshots__/language-list.test.js.snap
  src/ec/packages/ec-component-language-list/docs/overlay.md
  src/ec/packages/ec-component-message/__snapshots__/message.test.js.snap
  src/ec/packages/ec-component-search-form/__snapshots__/search-form.test.js.snap
  src/ec/packages/ec-component-site-header/README.md
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
  src/ec/packages/ec-component-site-header/demo/data.js
  src/ec/packages/ec-component-site-header/package.json
  src/ec/packages/ec-component-site-header/site-header.html.twig
  src/ec/packages/ec-component-site-header/site-header.story.js
  src/ec/packages/ec-component-site-header/site-header.test.js
  src/ec/packages/ec-component-timeline/__snapshots__/timeline.test.js.snap
  yarn.lock
Labels: pr: under review
