Repository ec-europa/ecl-twig, pull requests merged in 2019-03, with the labels that each got.

#42 feat: EC component select - INNO-1340
  src/ec/packages/ec-component-select/.npmignore
  src/ec/packages/ec-component-select/README.md
  src/ec/packages/ec-component-select/__snapshots__/select.test.js.snap
  src/ec/packages/ec-component-select/docs/select.md
  src/ec/packages/ec-component-select/package.json
  src/ec/packages/ec-component-select/select.html.twig
  src/ec/packages/ec-component-select/select.story.js
  src/ec/packages/ec-component-select/select.test.js
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: review needed

#37 feat: Ec component breadcrumb
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-breadcrumb/.npmignore
  src/ec/packages/ec-component-breadcrumb/README.md
  src/ec/packages/ec-component-breadcrumb/__snapshots__/breadcrumb.test.js.snap
  src/ec/packages/ec-component-breadcrumb/breadcrumb.html.twig
  src/ec/packages/ec-component-breadcrumb/breadcrumb.story.js
  src/ec/packages/ec-component-breadcrumb/breadcrumb.test.js
  src/ec/packages/ec-component-breadcrumb/docs/breadcrumb.md
  src/ec/packages/ec-component-breadcrumb/package.json
  src/ec/packages/ec-components/package.json
  src/eu/.storybook/preview-head.html
  utils/storybook-addon-code/src/index.js
  yarn.lock
Labels: pr: review needed

#45 chore: show raw html
  .eslintrc.js
  src/ec/.storybook/manager-head.html
  utils/storybook-addon-code/src/index.js
  utils/storybook-addon-code/src/register.jsx
Labels: pr: under review

#48 feat: EC component accordion - INNO-1344
  src/ec/packages/ec-component-accordion/.npmignore
  src/ec/packages/ec-component-accordion/README.md
  src/ec/packages/ec-component-accordion/__snapshots__/accordion.test.js.snap
  src/ec/packages/ec-component-accordion/accordion.html.twig
  src/ec/packages/ec-component-accordion/accordion.story.js
  src/ec/packages/ec-component-accordion/accordion.test.js
  src/ec/packages/ec-component-accordion/demo/data.js
  src/ec/packages/ec-component-accordion/docs/accordion.md
  src/ec/packages/ec-component-accordion/package.json
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: under review

#51 feat: add EC component file - INNO-1350
  src/ec/packages/ec-component-file/.npmignore
  src/ec/packages/ec-component-file/README.md
  src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
  src/ec/packages/ec-component-file/demo/data.js
  src/ec/packages/ec-component-file/docs/file.md
  src/ec/packages/ec-component-file/file.html.twig
  src/ec/packages/ec-component-file/file.story.js
  src/ec/packages/ec-component-file/file.test.js
  src/ec/packages/ec-component-file/package.json
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: review needed, pr: under review

#46 feat: Add expandable component
  src/ec/examples/composition/__snapshots__/composition.test.js.snap
  src/ec/packages/ec-component-accordion/__snapshots__/accordion.test.js.snap
  src/ec/packages/ec-component-button/__snapshots__/button.test.js.snap
  src/ec/packages/ec-component-button/button.html.twig
  src/ec/packages/ec-component-expandable/.npmignore
  src/ec/packages/ec-component-expandable/README.md
  src/ec/packages/ec-component-expandable/__snapshots__/expandable.test.js.snap
  src/ec/packages/ec-component-expandable/demo/data.js
  src/ec/packages/ec-component-expandable/docs/expandable.md
  src/ec/packages/ec-component-expandable/expandable.html.twig
  src/ec/packages/ec-component-expandable/expandable.story.js
  src/ec/packages/ec-component-expandable/expandable.test.js
  src/ec/packages/ec-component-expandable/package.json
  src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
  src/ec/packages/ec-component-language-list/__snapshots__/language-list.test.js.snap
  src/ec/packages/ec-component-search-form/__snapshots__/search-form.test.js.snap
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: review needed

#55 feat(button): improve quality, fix leak
  src/ec/packages/ec-component-accordion/__snapshots__/accordion.test.js.snap
  src/ec/packages/ec-component-button/button.html.twig
  src/ec/packages/ec-component-expandable/__snapshots__/expandable.test.js.snap
  src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
Labels: pr: under review

#57 docs: use `only` keyword
  docs/README.md
  docs/conventions.md
  docs/decisions/001-strip-whitespaces.md
  package.json
  src/ec/packages/ec-component-button/__snapshots__/button.test.js.snap
  src/ec/packages/ec-component-button/button.test.js
  src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
  src/ec/packages/ec-component-icon/icon.html.twig
  src/ec/packages/ec-component-link/__snapshots__/link.test.js.snap
  src/ec/packages/ec-component-link/link.html.twig
  src/ec/packages/ec-component-link/link.test.js
  src/ec/packages/ec-component-select/__snapshots__/select.test.js.snap
  src/ec/packages/ec-component-select/select.html.twig
  src/ec/packages/ec-component-select/select.test.js
  utils/test-utils/index.js
Labels: pr: under review

#49 feat: EC Hero Banner
  src/ec/packages/ec-component-hero-banner/.npmignore
  src/ec/packages/ec-component-hero-banner/README.md
  src/ec/packages/ec-component-hero-banner/__snapshots__/hero-banner.test.js.snap
  src/ec/packages/ec-component-hero-banner/docs/hero-banner.md
  src/ec/packages/ec-component-hero-banner/hero-banner.html.twig
  src/ec/packages/ec-component-hero-banner/hero-banner.story.js
  src/ec/packages/ec-component-hero-banner/hero-banner.test.js
  src/ec/packages/ec-component-hero-banner/package.json
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: under review

#58 refactor(icon): improve quality, add more tests
  src/ec/packages/ec-component-icon/__snapshots__/icon.test.js.snap
  src/ec/packages/ec-component-icon/icon.html.twig
  src/ec/packages/ec-component-icon/icon.test.js
Labels: pr: review needed

#59 refactor(text-area): improve quality, add more tests
  README.md
  docs/README.md
  src/ec/packages/ec-component-text-area/__snapshots__/text-area.test.js.snap
  src/ec/packages/ec-component-text-area/docs/text-area.md
  src/ec/packages/ec-component-text-area/text-area.html.twig
  src/ec/packages/ec-component-text-area/text-area.test.js
Labels: pr: review needed, pr: under review

#61 refactor(text-input): improve quality, add more tests
  src/ec/packages/ec-component-search-form/__snapshots__/search-form.test.js.snap
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
  src/ec/packages/ec-component-text-input/__snapshots__/text-input.test.js.snap
  src/ec/packages/ec-component-text-input/text-input.html.twig
  src/ec/packages/ec-component-text-input/text-input.test.js
Labels: pr: review needed

#66 refactor(card): improve quality
  src/ec/packages/ec-component-button/button.test.js
  src/ec/packages/ec-component-card/__snapshots__/card.test.js.snap
  src/ec/packages/ec-component-card/card.html.twig
  src/ec/packages/ec-component-card/card.test.js
  src/ec/packages/ec-component-card/package.json
  yarn.lock
Labels: pr: under review

#67 refactor(footer): improve quality
  src/ec/packages/ec-component-footer/__snapshots__/footer.test.js.snap
  src/ec/packages/ec-component-footer/footer.html.twig
  src/ec/packages/ec-component-footer/footer.test.js
  src/ec/packages/ec-component-link/link.test.js
Labels: pr: under review

#69 refactor(search-form): improve quality
  src/ec/packages/ec-component-search-form/__snapshots__/search-form.test.js.snap
  src/ec/packages/ec-component-search-form/package.json
  src/ec/packages/ec-component-search-form/search-form.html.twig
  src/ec/packages/ec-component-search-form/search-form.test.js
  yarn.lock
Labels: pr: under review

#73 fix: use appendChild instead of append for IE/Edge
  .eslintrc.js
  src/ec/packages/ec-component-accordion/accordion.story.js
  src/ec/packages/ec-component-breadcrumb/breadcrumb.story.js
  src/ec/packages/ec-component-contextual-navigation/contextual-navigation.story.js
  src/ec/packages/ec-component-expandable/expandable.story.js
  src/ec/packages/ec-component-file/file.story.js
  utils/storybook-addon-code/src/index.js
Labels: pr: under review

#68 refactor(language-list): improve quality
  src/ec/packages/ec-component-language-list/__snapshots__/language-list.test.js.snap
  src/ec/packages/ec-component-language-list/language-list-item.html.twig
  src/ec/packages/ec-component-language-list/language-list.html.twig
  src/ec/packages/ec-component-language-list/language-list.test.js
Labels: pr: review needed

#65 refactor(breadcrumb): improve quality
  src/ec/packages/ec-component-breadcrumb/README.md
  src/ec/packages/ec-component-breadcrumb/__snapshots__/breadcrumb.test.js.snap
  src/ec/packages/ec-component-breadcrumb/breadcrumb.html.twig
  src/ec/packages/ec-component-breadcrumb/breadcrumb.story.js
  src/ec/packages/ec-component-breadcrumb/breadcrumb.test.js
  src/ec/packages/ec-component-breadcrumb/docs/breadcrumb.md
  src/ec/packages/ec-component-breadcrumb/package.json
  yarn.lock
Labels: pr: under review

#72 refactor(page-header): improve quality
  src/ec/packages/ec-component-page-header/.npmignore
  src/ec/packages/ec-component-page-header/README.md
  src/ec/packages/ec-component-page-header/__snapshots__/page-header.test.js.snap
  src/ec/packages/ec-component-page-header/docs/page-header.md
  src/ec/packages/ec-component-page-header/page-header.html.twig
  src/ec/packages/ec-component-page-header/page-header.story.js
  src/ec/packages/ec-component-page-header/page-header.test.js
Labels: pr: under review

#70 refactor(site-header): improve quality
  src/ec/packages/ec-component-site-header/.npmignore
  src/ec/packages/ec-component-site-header/README.md
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
  src/ec/packages/ec-component-site-header/docs/site-header.md
  src/ec/packages/ec-component-site-header/package.json
  src/ec/packages/ec-component-site-header/site-header.html.twig
  src/ec/packages/ec-component-site-header/site-header.story.js
  src/ec/packages/ec-component-site-header/site-header.test.js
  yarn.lock
Labels: pr: review needed

#76 feat: EC Gallery - INNO-1384
  src/ec/packages/ec-component-gallery/.npmignore
  src/ec/packages/ec-component-gallery/README.md
  src/ec/packages/ec-component-gallery/__snapshots__/gallery.test.js.snap
  src/ec/packages/ec-component-gallery/demo/data.js
  src/ec/packages/ec-component-gallery/gallery-item.html.twig
  src/ec/packages/ec-component-gallery/gallery-overlay.html.twig
  src/ec/packages/ec-component-gallery/gallery.html.twig
  src/ec/packages/ec-component-gallery/gallery.story.js
  src/ec/packages/ec-component-gallery/gallery.test.js
  src/ec/packages/ec-component-gallery/package.json
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: under review
