Repository ec-europa/ecl-twig, pull requests merged in 2019-12, with the labels that each got.

#251 refactor(banner): specs file, test and story adapted - TWIG-148
  php/php_storybook/resources/fix-data.js
  src/ec/packages/ec-component-message/message.story.js
  src/ec/packages/ec-component-page-banner/__snapshots__/page-banner.test.js.snap
  src/ec/packages/ec-component-page-banner/adapter.js
  src/ec/packages/ec-component-page-banner/demo/data--align-left.js
  src/ec/packages/ec-component-page-banner/demo/data--default.js
  src/ec/packages/ec-component-page-banner/demo/data--image-shade.js
  src/ec/packages/ec-component-page-banner/demo/data--image.js
  src/ec/packages/ec-component-page-banner/demo/data--primary.js
  src/ec/packages/ec-component-page-banner/demo/data.js
  src/ec/packages/ec-component-page-banner/ecl-page-banner.html.twig
  src/ec/packages/ec-component-page-banner/page-banner.story.js
  src/ec/packages/ec-component-page-banner/page-banner.test.js
Labels: pr: under review

#253 refactor(footer-harmonised): spec files - TWIG-150
  php/php_storybook/resources/fix-data.js
  src/ec/packages/ec-component-footer-harmonised/adapter.js
  src/ec/packages/ec-component-footer-harmonised/demo/data--group1.js
  src/ec/packages/ec-component-footer-harmonised/demo/data--group2.js
  src/ec/packages/ec-component-footer-harmonised/footer-harmonised.story.js
  src/ec/packages/ec-component-footer-harmonised/footer-harmonised.test.js
Labels: pr: under review

#255 refactor(static-resources): Symbolic links instead of physical files - TWIG-153
  static/images/logo--en.svg
  static/images/logo--fr.svg
  static/images/logo--mute.svg
Labels: pr: under review

#256 refactor(page-headers): specs files aligned with ECL - TWIG-146
  php/php_storybook/README.md
  php/php_storybook/resources/fix-data.js
  php/php_storybook/scripts/generate-data-files.js
  src/ec/packages/ec-component-page-header-core/__snapshots__/page-header-core.test.js.snap
  src/ec/packages/ec-component-page-header-core/adapter.js
  src/ec/packages/ec-component-page-header-core/demo/data--meta-title-description.js
  src/ec/packages/ec-component-page-header-core/demo/data--meta-title.js
  src/ec/packages/ec-component-page-header-core/demo/data--title.js
  src/ec/packages/ec-component-page-header-core/demo/data.js
  src/ec/packages/ec-component-page-header-core/page-header-core.story.js
  src/ec/packages/ec-component-page-header-core/page-header-core.test.js
  src/ec/packages/ec-component-page-header-harmonised/adapter.js
  src/ec/packages/ec-component-page-header-harmonised/demo/data--meta-title-description.js
  src/ec/packages/ec-component-page-header-harmonised/demo/data--meta-title.js
  src/ec/packages/ec-component-page-header-harmonised/demo/data--title.js
  src/ec/packages/ec-component-page-header-harmonised/demo/data.js
  src/ec/packages/ec-component-page-header-harmonised/page-header-harmonised.story.js
  src/ec/packages/ec-component-page-header-harmonised/page-header-harmonised.test.js
  src/ec/packages/ec-component-page-header-standardised/adapter.js
  src/ec/packages/ec-component-page-header-standardised/demo/data--meta-title-description.js
  src/ec/packages/ec-component-page-header-standardised/demo/data--meta-title.js
  src/ec/packages/ec-component-page-header-standardised/demo/data--title.js
  src/ec/packages/ec-component-page-header-standardised/demo/data.js
  src/ec/packages/ec-component-page-header-standardised/page-header-standardised.story.js
  src/ec/packages/ec-component-page-header-standardised/page-header-standardised.test.js
  src/ec/packages/ec-component-skip-link/README.md
Labels: pr: under review

#257 refactor(libraries): updating libs
  package.json
  yarn.lock
Labels: pr: review needed

#264 fix(deps): Uprading serialize-javascript to get rid of warning - TWIG-166
  package.json
  yarn.lock
Labels: pr: under review

#261 feat(language-list): Icon removed - TWIG-165
  src/ec/packages/ec-component-language-list/__snapshots__/language-list.test.js.snap
  src/ec/packages/ec-component-language-list/ecl-language-list-overlay.html.twig
  src/ec/packages/ec-component-language-list/package.json
  src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
Labels: pr: under review

#260 feat(diff): Command for diffing components added - TWIG-119
  .drone.yml
  docs/getting-started.md
  package.json
  php/php_storybook/resources/helpers.php
  php/php_storybook/scripts/diff.js
  php/php_storybook/scripts/generate-data-files.js
  php/php_storybook/scripts/render.js
  php/php_storybook/scripts/render.php
  src/ec/packages/ec-component-inpage-navigation/demo/data.js
  src/ec/packages/ec-component-inpage-navigation/demo/page-filler.js
  src/ec/packages/ec-component-inpage-navigation/inpage-navigation.story.js
  yarn.lock
Labels: pr: under review

#263 refactor(tag): Using ECL specs - TWIG-168
  src/ec/packages/ec-component-tag/__snapshots__/tag.test.js.snap
  src/ec/packages/ec-component-tag/adapter.js
  src/ec/packages/ec-component-tag/demo/data--button.js
  src/ec/packages/ec-component-tag/demo/data--link.js
  src/ec/packages/ec-component-tag/demo/data--removable.js
  src/ec/packages/ec-component-tag/package.json
  yarn.lock
Labels: pr: under review

#265 feat(menus): Adding components (standardised and harmonised) - Twig 162
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-menu-harmonised/README.md
  src/ec/packages/ec-component-menu-harmonised/__snapshots__/menu-harmonised.test.js.snap
  src/ec/packages/ec-component-menu-harmonised/adapter.js
  src/ec/packages/ec-component-menu-harmonised/demo/data--group1.js
  src/ec/packages/ec-component-menu-harmonised/demo/data--group2.js
  src/ec/packages/ec-component-menu-harmonised/ecl-menu-harmonised-item.html.twig
  src/ec/packages/ec-component-menu-harmonised/ecl-menu-harmonised.html.twig
  src/ec/packages/ec-component-menu-harmonised/menu-harmonised.story.js
  src/ec/packages/ec-component-menu-harmonised/menu-harmonised.test.js
  src/ec/packages/ec-component-menu-harmonised/package.json
  src/ec/packages/ec-component-menu-standardised/.npmignore
  src/ec/packages/ec-component-menu-standardised/README.md
  src/ec/packages/ec-component-menu-standardised/__snapshots__/menu-standardised.test.js.snap
  src/ec/packages/ec-component-menu-standardised/adapter.js
  src/ec/packages/ec-component-menu-standardised/demo/data--en.js
  src/ec/packages/ec-component-menu-standardised/demo/data--fr.js
  src/ec/packages/ec-component-menu-standardised/ecl-menu-standardised-item.html.twig
  src/ec/packages/ec-component-menu-standardised/ecl-menu-standardised.html.twig
  src/ec/packages/ec-component-menu-standardised/menu-standardised.story.js
  src/ec/packages/ec-component-menu-standardised/menu-standardised.test.js
  src/ec/packages/ec-component-menu-standardised/package.json
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/demo/data--group1.js
  src/ec/packages/ec-component-site-header-harmonised/demo/data--group2.js
  src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/adapter.js
  src/ec/packages/ec-component-site-header-standardised/demo/data--en.js
  src/ec/packages/ec-component-site-header-standardised/demo/data--fr.js
  src/ec/packages/ec-component-site-header-standardised/ecl-menu.html.twig
  src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
  yarn.lock
Labels: pr: modification needed

#267 fix(hide-not-ready-components): Hiding site headers containing a menu - TWIG-161
  src/ec/packages/ec-component-menu-harmonised/menu-harmonised.story.js.bckp
  src/ec/packages/ec-component-menu-standardised/menu-standardised.story.js.bckp
  src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js.bckp
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js.bckp
Labels: pr: under review

#272 fix(site-headers): Add arrow icon to login link - TWIG-183
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap
  src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig
  src/ec/packages/ec-component-site-header-core/package.json
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
  src/ec/packages/ec-component-site-header-harmonised/package.json
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
  src/ec/packages/ec-component-site-header-standardised/package.json
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: under review

#266 fix: programmatically setting the status of the drone builds
  scripts/set-netlify-deployment-status.js
Labels: pr: review needed

#274 refactor(menu): all to one - TWIG-179
  src/ec/packages/ec-component-menu-harmonised/__snapshots__/menu-harmonised.test.js.snap
  src/ec/packages/ec-component-menu-harmonised/demo/data--group2.js
  src/ec/packages/ec-component-menu-harmonised/ecl-menu-harmonised-item.html.twig
  src/ec/packages/ec-component-menu-harmonised/ecl-menu-harmonised.html.twig
  src/ec/packages/ec-component-menu-harmonised/menu-harmonised.story.js
  src/ec/packages/ec-component-menu-harmonised/menu-harmonised.story.js.bckp
  src/ec/packages/ec-component-menu-harmonised/menu-harmonised.test.js
  src/ec/packages/ec-component-menu-harmonised/package.json
  src/ec/packages/ec-component-menu-standardised/.npmignore
  src/ec/packages/ec-component-menu-standardised/CHANGELOG.md
  src/ec/packages/ec-component-menu-standardised/README.md
  src/ec/packages/ec-component-menu-standardised/adapter.js
  src/ec/packages/ec-component-menu-standardised/demo/data--en.js
  src/ec/packages/ec-component-menu-standardised/demo/data--fr.js
  src/ec/packages/ec-component-menu-standardised/ecl-menu-standardised-item.html.twig
  src/ec/packages/ec-component-menu-standardised/menu-standardised.story.js
  src/ec/packages/ec-component-menu-standardised/menu-standardised.story.js.bckp
  src/ec/packages/ec-component-menu/CHANGELOG.md
  src/ec/packages/ec-component-menu/README.md
  src/ec/packages/ec-component-menu/__snapshots__/menu.test.js.snap
  src/ec/packages/ec-component-menu/adapter.js
  src/ec/packages/ec-component-menu/demo/data--en.js
  src/ec/packages/ec-component-menu/demo/data--fr.js
  src/ec/packages/ec-component-menu/demo/data--group1.js
  src/ec/packages/ec-component-menu/demo/data--group2.js
  src/ec/packages/ec-component-menu/ecl-menu-item.html.twig
  src/ec/packages/ec-component-menu/ecl-menu.html.twig
  src/ec/packages/ec-component-menu/menu.story.js.bckp
  src/ec/packages/ec-component-menu/menu.test.js
  src/ec/packages/ec-component-menu/package.json
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/demo/data--group1.js
  src/ec/packages/ec-component-site-header-harmonised/demo/data--group2.js
  src/ec/packages/ec-component-site-header-harmonised/ecl-menu.html.twig
  src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
  src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/demo/data--en.js
  src/ec/packages/ec-component-site-header-standardised/demo/data--fr.js
  src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: review needed
