Repository ec-europa/ecl-twig, pull requests merged in 2020-03, with the labels that each got.

#349 feat(knobs): fact and figures show/hiding elements and grouping knobs - FRONT-866
  src/ec/packages/ec-component-fact-figures/fact-figures.story.js
Labels: tag: enhancement

#346 feat(knobs): Blockquote panel with three sub-panels, buttons for show/hiding - FRONT-803
  src/ec/packages/ec-component-blockquote/blockquote.story.js
Labels: tag: enhancement

#347 feat(knobs): Button show/hiding elements and grouping knobs - FRONT-865
  src/ec/packages/ec-component-button/button.story.js
Labels: tag: enhancement

#350 fix(notes): The template inclusion example in the notes panel is now matching the status of the component - FRONT-891
  utils/storybook-addon-notes/src/index.js
Labels: pr: under review, tag: bug fix

#351 fix(button): fixing the example in the notes tab, improving knobs - FRONT-893
  src/ec/packages/ec-component-button/button.story.js
Labels: pr: under review, tag: enhancement

#359 refactor(demo): Text input, grouping knobs, adding states - FRONT-903
  src/ec/packages/ec-component-text-input/adapter.js
  src/ec/packages/ec-component-text-input/text-input.story.js
Labels: pr: review needed, tag: enhancement

#358 refactor(demo): Radio, grouping knobs - FRONT-902
  src/ec/packages/ec-component-radio/radio.story.js
Labels: pr: review needed, tag: enhancement

#352 refactor(demo): File, mandatory/optional knobs - FRONT-875
  src/ec/packages/ec-component-file/file.story.js
Labels: pr: review needed, tag: enhancement

#357 refactor(demo): Checkbox, optional/mandatory knobs - FRONT-901
  src/ec/packages/ec-component-checkbox/checkbox.story.js
Labels: pr: review needed, tag: enhancement

#356 refactor(demo): Date block, mandatory/optional knobs, added stories for statuses - FRONT-900
  src/ec/packages/ec-component-date-block/date-block.story.js
Labels: pr: review needed, tag: enhancement

#360 feat(media-container): Adding support for embedded media - FRONT-941
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-media-container/README.md
  src/ec/packages/ec-component-media-container/__snapshots__/media-container.test.js.snap
  src/ec/packages/ec-component-media-container/demo/data--embed.js
  src/ec/packages/ec-component-media-container/demo/data--image.js
  src/ec/packages/ec-component-media-container/demo/data--video.js
  src/ec/packages/ec-component-media-container/ecl-media-container.html.twig
  src/ec/packages/ec-component-media-container/media-container.story.js
  src/ec/packages/ec-component-media-container/media-container.test.js
  src/ec/packages/ec-component-media-container/package.json
  yarn.lock
Labels: tag: new feature

#355 refactor(demo): Page Header Standardised, grouping knobs - FRONT-898
  src/ec/packages/ec-component-page-header-standardised/adapter.js
  src/ec/packages/ec-component-page-header-standardised/ecl-page-header-standardised.html.twig
  src/ec/packages/ec-component-page-header-standardised/page-header-standardised.story.js
Labels: pr: review needed, tag: enhancement

#354 refactor(demo): Page Header Harmonised, grouping knobs - FRONT-878
  src/ec/packages/ec-component-page-header-harmonised/adapter.js
  src/ec/packages/ec-component-page-header-harmonised/ecl-page-header-harmonised.html.twig
  src/ec/packages/ec-component-page-header-harmonised/page-header-harmonised.story.js
Labels: pr: review needed, tag: enhancement

#353 refactor(demo): Page header core, optional/mandatory groups - FRONT-877
  src/ec/packages/ec-component-page-header-core/adapter.js
  src/ec/packages/ec-component-page-header-core/ecl-page-header-core.html.twig
  src/ec/packages/ec-component-page-header-core/page-header-core.story.js
Labels: pr: review needed, tag: enhancement

#361 fix(notes): Replacing decode-html with he, updating plugin to use it on all the strings - FRONT-945
  package.json
  src/ec/packages/ec-component-file-upload/file-upload.story.js
  src/ec/packages/ec-component-media-container/media-container.story.js
  utils/storybook-addon-notes/src/index.js
  yarn.lock
Labels: tag: bug fix

#369 refactor(demo): Link, grouping knobs FRONT-908
  src/ec/packages/ec-component-link/link.story.js
Labels: pr: review needed, tag: enhancement

#368 refactor(demo): Skip Link, Grouping knobs - FRONT-911
  src/ec/packages/ec-component-skip-link/ecl-skip-link.html.twig
  src/ec/packages/ec-component-skip-link/skip-link.story.js
Labels: pr: review needed, tag: enhancement

#367 refactor(demo): Search form, grouping knobs - FRONT-907
  src/ec/packages/ec-component-search-form/demo/data.js
  src/ec/packages/ec-component-search-form/ecl-search-form.html.twig
  src/ec/packages/ec-component-search-form/search-form.story.js
  src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
Labels: pr: review needed, tag: enhancement

#362 fix(button): Fixing extra_attributes knobs, adding states group - FRONT-947
  package.json
  src/ec/packages/ec-component-button/button.story.js
  utils/story-utils/README.md
  utils/story-utils/package.json
  utils/story-utils/src/index.js
  yarn.lock
Labels: tag: enhancement

#363 fix(text-field): Fixing extra_attributes knobs - FRONT-948
  src/ec/packages/ec-component-text-input/text-input.story.js
  utils/story-utils/src/index.js
Labels: pr: review needed, tag: bug fix

#365 fix(php-storybook): Fixing icons and images in the distributed php-storybook - FRONT-946
  php/php_storybook/resources/fix-build.js
  php/php_storybook/resources/get-assets.js
Labels: tag: bug fix

#366 refactor(demo): Select, grouping knobs - FRONT-906
  src/ec/packages/ec-component-select/select.story.js
Labels: pr: review needed, tag: enhancement

#372 refactor(demo): Form components alignment - FRONT-953
  src/ec/packages/ec-component-checkbox/checkbox.story.js
  src/ec/packages/ec-component-file/file.story.js
  src/ec/packages/ec-component-radio/radio.story.js
  src/ec/packages/ec-component-search-form/search-form.story.js
  utils/story-utils/src/index.js
Labels: tag: enhancement

#376 refactor(demo): Icon, optional/mandatory elements - FRONT-914
  src/ec/packages/ec-component-button/button.story.js
  src/ec/packages/ec-component-icon/adapter.js
  src/ec/packages/ec-component-icon/demo/data--audio.js
  src/ec/packages/ec-component-icon/demo/data--facebook.js
  src/ec/packages/ec-component-icon/demo/data--success.js
  src/ec/packages/ec-component-icon/demo/data--ui.js
  src/ec/packages/ec-component-icon/icon.story.js
  utils/story-utils/src/index.js
Labels: pr: under review, tag: enhancement

#377 fix(ecl-diff): Replacing decode-html with he - FRONT-958
  php/php_storybook/scripts/ecl-diff.js
Labels: pr: review needed, tag: bug fix

#364 refactor(demo): Text Area, States, optional/mandatory knobs - FRONT-904
  src/ec/packages/ec-component-text-area/adapter.js
  src/ec/packages/ec-component-text-area/text-area.story.js
Labels: tag: enhancement

#380 fix(site-header): Setting overlay to true for the language list - FRONT-959
  php/php_storybook/scripts/ecl-diff.js
  src/ec/packages/ec-component-language-list/__snapshots__/language-list.test.js.snap
  src/ec/packages/ec-component-language-list/ecl-language-list.html.twig
  src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap
  src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
  src/ec/packages/ec-component-site-header/adapter.js
  src/ec/packages/ec-component-site-header/ecl-site-header.html.twig
  src/ec/packages/ec-component-site-header/site-header.story.js
Labels: tag: bug fix

#373 refactor(demo): hero-banner optional/mandatory knobs - FRONT-912
  src/ec/packages/ec-component-hero-banner/adapter.js
  src/ec/packages/ec-component-hero-banner/ecl-hero-banner.html.twig
  src/ec/packages/ec-component-hero-banner/hero-banner.story.js
  utils/story-utils/src/index.js
Labels: pr: review needed, tag: enhancement

#379 refactor(demo): Site Header Core, optional/mandatory knobs - FRONT-917
  src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap
  src/ec/packages/ec-component-site-header-core/adapter.js
  src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig
  src/ec/packages/ec-component-site-header-core/site-header-core.story.js
  utils/story-utils/src/index.js
Labels: pr: under review, tag: enhancement

#374 refactor(demo): Pagebanner optional/mandatory knobs - FRONT-913
  src/ec/packages/ec-component-page-banner/adapter.js
  src/ec/packages/ec-component-page-banner/page-banner.story.js
Labels: pr: under review, tag: enhancement

#378 refactor(demo): Tags, optional/mandatory knobs - FRONT-922
  src/ec/packages/ec-component-tag/tag.story.js
  yarn.lock
Labels: tag: enhancement

#375 refactor(demo): Messages, optional/mandatory knobs - FRONT-916
  src/ec/packages/ec-component-button/button.story.js
  src/ec/packages/ec-component-message/ecl-message.html.twig
  src/ec/packages/ec-component-message/message.story.js
  yarn.lock
Labels: tag: enhancement

#383 refactor(demo): Social media follow, mandatory/optional knobs - FRONT-920
  src/ec/packages/ec-component-social-media-follow/demo/data.js
  src/ec/packages/ec-component-social-media-follow/ecl-social-media-follow.html.twig
  src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js
Labels: tag: enhancement

#384 refactor(demo): Site Header Standardised, mandatory/optional knobs - FRONT-919
  src/ec/packages/ec-component-site-header-core/site-header-core.story.js
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/adapter.js
  src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
  utils/story-utils/src/index.js
Labels: tag: enhancement

#381 refactor(demo): Accordion(2) knobs and labels added - FRONT-910
  src/ec/packages/ec-component-accordion2/accordion2.story.js
Labels: pr: review needed, tag: enhancement

#385 refactor(demo): Accordion knobs and labels added - FRONT 909
  src/ec/packages/ec-component-accordion/accordion.story.js
Labels: pr: review needed, tag: enhancement

#382 refactor(demo): Inpage navigation, optional/mandatory knobs - FRONT-927
  src/ec/packages/ec-component-inpage-navigation/README.md
  src/ec/packages/ec-component-inpage-navigation/ecl-inpage-navigation.html.twig
  src/ec/packages/ec-component-inpage-navigation/inpage-navigation.story.js
Labels: tag: enhancement

#386 refactor(knobs): timeline knobs and labels - FRONT-923
  src/ec/packages/ec-component-timeline/timeline.story.js
Labels: pr: review needed, tag: enhancement

#387 refactor(demo): Social media share, optional/mandatory knobs - FRONT-921
  src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js
  src/ec/packages/ec-component-social-media-share/demo/data.js
  src/ec/packages/ec-component-social-media-share/ecl-social-media-share.html.twig
  src/ec/packages/ec-component-social-media-share/social-media-share.story.js
  utils/story-utils/src/index.js
Labels: tag: enhancement

#391 fix(demo): Timeline, adding ids, reorganisation of some knobs - FRONT-972
  src/ec/packages/ec-component-timeline/README.md
  src/ec/packages/ec-component-timeline/__snapshots__/timeline.test.js.snap
  src/ec/packages/ec-component-timeline/adapter.js
  src/ec/packages/ec-component-timeline/demo/data.js
  src/ec/packages/ec-component-timeline/ecl-timeline.html.twig
  src/ec/packages/ec-component-timeline/timeline.story.js
Labels: tag: bug fix

#390 refactor(knobs): Datepicker - Mandatory/optional knobs - FRONT-905
  src/ec/packages/ec-component-datepicker/datepicker.story.js
Labels: pr: under review, tag: enhancement

#389 refactor(demo): Site header harmonised - Mandatory/optional knobs - FRONT-918
  src/ec/packages/ec-component-site-header-core/site-header-core.story.js
  src/ec/packages/ec-component-site-header-harmonised/README.md
  src/ec/packages/ec-component-site-header-harmonised/adapter.js
  src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
  src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
  utils/story-utils/src/index.js
Labels: pr: under review, tag: enhancement

#393 refactor(demo): Language list, optional/mandatory knobs, fixing the notes plugin - FRONT-925
  src/ec/packages/ec-component-language-list/adapter.js
  src/ec/packages/ec-component-language-list/demo/data--overlay.js
  src/ec/packages/ec-component-language-list/demo/data--splash.js
  src/ec/packages/ec-component-language-list/ecl-language-list-item.html.twig
  src/ec/packages/ec-component-language-list/language-list.story.js
  utils/storybook-addon-notes/src/index.js
Labels: pr: under review, tag: enhancement

#394 feat(menuV2): Implementation, green diff with ECL - FRONT-991
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-menu/README.md
  src/ec/packages/ec-component-menu/__snapshots__/menu.test.js.snap
  src/ec/packages/ec-component-menu/adapter.js
  src/ec/packages/ec-component-menu/ecl-menu-item.html.twig
  src/ec/packages/ec-component-menu/ecl-menu.html.twig
  src/ec/packages/ec-component-menu/menu.story.js
  src/ec/packages/ec-component-menu/package.json
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/adapter.js
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  yarn.lock
Labels: tag: breaking change, tag: new feature
