Repository ec-europa/ecl-twig, pull requests merged in 2020-07, with the labels that each got.

#483 feat(webpack): Alternative way to disable progressPlugin - FRONT-1251
  php/ec/.storybook/webpack.config.js
  src/ec/storybook/.storybook/webpack.config.js
  src/eu/storybook/.storybook/webpack.config.js
Labels: pr: review needed, tag: internal

#485 feat(knobs): Replacing select elements with optionsKnob in multiple stories - FRONT-1253
  src/ec/packages/ec-component-accordion/accordion.story.js
  src/ec/packages/ec-component-accordion2/accordion2.story.js
  src/ec/packages/ec-component-breadcrumb-core/breadcrumb-core.story.js
  src/ec/packages/ec-component-breadcrumb-harmonised/breadcrumb-harmonised.story.js
  src/ec/packages/ec-component-breadcrumb-standardised/breadcrumb-standardised.story.js
  src/ec/packages/ec-component-breadcrumb/breadcrumb.story.js
  src/ec/packages/ec-component-card/card.story.js
  src/ec/packages/ec-component-card/ecl-card.html.twig
  src/ec/packages/ec-component-datepicker/datepicker.story.js
  src/ec/packages/ec-component-dropdown-legacy/dropdown-legacy.story.js
  src/ec/packages/ec-component-expandable/expandable.story.js
  src/ec/packages/ec-component-file/file.story.js
  src/ec/packages/ec-component-footer/footer.story.js
  src/ec/packages/ec-component-gallery/__snapshots__/gallery.test.js.snap
  src/ec/packages/ec-component-gallery/adapter.js
  src/ec/packages/ec-component-gallery/gallery.story.js
  src/ec/packages/ec-component-language-list/language-list.story.js
  src/ec/packages/ec-component-menu-legacy/menu-legacy.story.js
  src/ec/packages/ec-component-menu/menu.story.js
  src/ec/packages/ec-component-message/message.story.js
  src/ec/packages/ec-component-pagination/pagination.story.js
  src/ec/packages/ec-component-search-form/search-form.story.js
  src/ec/packages/ec-component-site-header-core/site-header-core.story.js
  src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
  src/ec/packages/ec-component-site-header/site-header.story.js
  src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js
  src/ec/packages/ec-component-social-media-share/social-media-share.story.js
  src/ec/packages/ec-component-tag/tag.story.js
  src/ec/packages/ec-component-timeline/timeline.story.js
  utils/story-utils/src/index.js
Labels: pr: review needed, tag: enhancement

#488 chore: update drone pipeline - FRONT-1255
  .drone.yml
Labels: pr: review needed, tag: internal

#489 feat(stories): Migration to CSF format - FRONT-1117
  src/ec/packages/ec-component-accordion/accordion.story.js
  src/ec/packages/ec-component-accordion2/accordion2.story.js
  src/ec/packages/ec-component-blockquote/blockquote.story.js
  src/ec/packages/ec-component-breadcrumb-core/breadcrumb-core.story.js
  src/ec/packages/ec-component-breadcrumb-harmonised/breadcrumb-harmonised.story.js
  src/ec/packages/ec-component-breadcrumb-standardised/breadcrumb-standardised.story.js
  src/ec/packages/ec-component-breadcrumb/breadcrumb.story.js
  src/ec/packages/ec-component-button/button.story.js
  src/ec/packages/ec-component-card/card.story.js
  src/ec/packages/ec-component-checkbox/checkbox.story.js
  src/ec/packages/ec-component-contextual-navigation/contextual-navigation.story.js
  src/ec/packages/ec-component-date-block/date-block.story.js
  src/ec/packages/ec-component-datepicker/datepicker.story.js
  src/ec/packages/ec-component-description-list/description-list.story.js
  src/ec/packages/ec-component-dropdown-legacy/dropdown-legacy.story.js
  src/ec/packages/ec-component-expandable/expandable.story.js
  src/ec/packages/ec-component-fact-figures/fact-figures.story.js
  src/ec/packages/ec-component-file-upload/file-upload.story.js
  src/ec/packages/ec-component-file/file.story.js
  src/ec/packages/ec-component-footer-core/footer-core.story.js
  src/ec/packages/ec-component-footer-harmonised/footer-harmonised.story.js
  src/ec/packages/ec-component-footer-standardised/footer-standardised.story.js
  src/ec/packages/ec-component-footer/footer.story.js
  src/ec/packages/ec-component-gallery/gallery.story.js
  src/ec/packages/ec-component-hero-banner/hero-banner.story.js
  src/ec/packages/ec-component-icon/icon.story.js
  src/ec/packages/ec-component-inpage-navigation/inpage-navigation.story.js
  src/ec/packages/ec-component-label/label.story.js
  src/ec/packages/ec-component-language-list/language-list.story.js
  src/ec/packages/ec-component-link/link.story.js
  src/ec/packages/ec-component-media-container/media-container.story.js
  src/ec/packages/ec-component-menu-legacy/menu-legacy.story.js
  src/ec/packages/ec-component-menu/menu.story.js
  src/ec/packages/ec-component-message/message.story.js
  src/ec/packages/ec-component-ordered-list/ordered-list.story.js
  src/ec/packages/ec-component-page-banner/page-banner.story.js
  src/ec/packages/ec-component-page-header-core/page-header-core.story.js
  src/ec/packages/ec-component-page-header-harmonised/page-header-harmonised.story.js
  src/ec/packages/ec-component-page-header-standardised/page-header-standardised.story.js
  src/ec/packages/ec-component-page-header/page-header.story.js
  src/ec/packages/ec-component-pagination/pagination.story.js
  src/ec/packages/ec-component-radio/radio.story.js
  src/ec/packages/ec-component-search-form/search-form.story.js
  src/ec/packages/ec-component-select/select.story.js
  src/ec/packages/ec-component-site-header-core/site-header-core.story.js
  src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
  src/ec/packages/ec-component-site-header/site-header.story.js
  src/ec/packages/ec-component-skip-link/skip-link.story.js
  src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js
  src/ec/packages/ec-component-social-media-share/social-media-share.story.js
  src/ec/packages/ec-component-table/table.story.js
  src/ec/packages/ec-component-tag/tag.story.js
  src/ec/packages/ec-component-text-area/text-area.story.js
  src/ec/packages/ec-component-text-input/text-input.story.js
  src/ec/packages/ec-component-timeline/timeline.story.js
  src/ec/packages/ec-component-unordered-list/unordered-list.story.js
Labels: pr: review needed, tag: enhancement

#493 fix(inpage-navigation): removing hidden attribute - FRONT-1265
  src/ec/packages/ec-component-inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/ec/packages/ec-component-inpage-navigation/ecl-inpage-navigation.html.twig
  src/ec/packages/ec-component-inpage-navigation/package.json
  yarn.lock
Labels: tag: bug fix

#490 feat(scripts): Removing legacy scripts from package.json - FRONT-1257
  docs/getting-started.md
  package.json
  php/php_storybook/package.json
  php/php_storybook/scripts/render.js
  src/ec/storybook/.storybook/environment.js
Labels: pr: review needed, tag: internal

#491 feat(ci): Deploying both js and php storybook(s) on netlify - FRONT-1236
  .drone.yml
  docs/getting-started.md
  package.json
  scripts/set-netlify-deployment-status.js
  yarn.lock
Labels: tag: internal

#492 feat(select): Adding multiple select - FRONT-1261
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-select.html.twig
  src/ec/packages/ec-component-select/README.md
  src/ec/packages/ec-component-select/__snapshots__/select.test.js.snap
  src/ec/packages/ec-component-select/adapter.js
  src/ec/packages/ec-component-select/demo/data--multiple.js
  src/ec/packages/ec-component-select/demo/data--single.js
  src/ec/packages/ec-component-select/demo/data.js
  src/ec/packages/ec-component-select/ecl-select.html.twig
  src/ec/packages/ec-component-select/package.json
  src/ec/packages/ec-component-select/select.story.js
  src/ec/packages/ec-component-select/select.test.js
  utils/story-utils/src/index.js
  yarn.lock
Labels: tag: new feature

#495 feat(footer-standardised): Adding EU version - FRONT-1264
  package.json
  php/ec/.storybook/main.js
  php/php_storybook/scripts/ecl-diff.js
  php/php_storybook/scripts/generate-data-files.js
  php/php_storybook/scripts/render.js
  php/php_storybook/scripts/render.php
  src/ec/packages/ec-component-fact-figures/__snapshots__/fact-figures.test.js.snap
  src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
  src/ec/packages/ec-component-footer-core/__snapshots__/footer-core.test.js.snap
  src/ec/packages/ec-component-footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
  src/ec/packages/ec-component-footer-standardised/README.md
  src/ec/packages/ec-component-footer-standardised/__snapshots__/footer-standardised.test.js.snap
  src/ec/packages/ec-component-footer-standardised/adapter.js
  src/ec/packages/ec-component-footer-standardised/demo/data--eu.js
  src/ec/packages/ec-component-footer-standardised/ecl-footer-standardised.html.twig
  src/ec/packages/ec-component-footer-standardised/footer-standardised.story.js
  src/ec/packages/ec-component-footer-standardised/footer-standardised.test.js
  src/ec/packages/ec-component-footer-standardised/package.json
  src/ec/packages/ec-component-footer/__snapshots__/footer.test.js.snap
  src/ec/packages/ec-component-gallery/__snapshots__/gallery.test.js.snap
  src/ec/packages/ec-component-hero-banner/__snapshots__/hero-banner.test.js.snap
  src/ec/packages/ec-component-link/README.md
  src/ec/packages/ec-component-link/ecl-link.html.twig
  src/ec/packages/ec-component-page-banner/__snapshots__/page-banner.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  utils/data-utils/src/index.js
  yarn.lock
Labels: pr: under review, tag: new feature

#494 feat(footer-core): Adding EU version - FRONT-1262
  src/ec/packages/ec-component-footer-core/__snapshots__/footer-core.test.js.snap
  src/ec/packages/ec-component-footer-core/adapter.js
  src/ec/packages/ec-component-footer-core/demo/data--eu.js
  src/ec/packages/ec-component-footer-core/ecl-footer-core.html.twig
  src/ec/packages/ec-component-footer-core/footer-core.story.js
  src/ec/packages/ec-component-footer-core/footer-core.test.js
  src/ec/packages/ec-component-footer-core/package.json
  yarn.lock
Labels: pr: under review, tag: new feature

#496 feat(footer-harmonised): Adapting template for EU, adding EU demo - FRONT-1263
  src/ec/packages/ec-component-footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
  src/ec/packages/ec-component-footer-harmonised/adapter.js
  src/ec/packages/ec-component-footer-harmonised/demo/data--eu.js
  src/ec/packages/ec-component-footer-harmonised/ec-footer-harmonised.story.js
  src/ec/packages/ec-component-footer-harmonised/ecl-footer-harmonised.html.twig
  src/ec/packages/ec-component-footer-harmonised/eu-footer-harmonised.story.js
  src/ec/packages/ec-component-footer-harmonised/footer-harmonised.test.js
  src/ec/packages/ec-component-footer-harmonised/package.json
  src/ec/storybook/.storybook/main.js
  src/eu/storybook/.storybook/main.js
  yarn.lock
Labels: pr: under review, tag: new feature

#497 feat(breadcrumbs): Adding EU demo for all the breadcrumbs - FRONT-1266
  src/ec/packages/ec-component-breadcrumb-core/__snapshots__/breadcrumb-core.test.js.snap
  src/ec/packages/ec-component-breadcrumb-core/breadcrumb-core.story.js
  src/ec/packages/ec-component-breadcrumb-core/breadcrumb-core.test.js
  src/ec/packages/ec-component-breadcrumb-core/demo/data--eu.js
  src/ec/packages/ec-component-breadcrumb-core/demo/data--simple--eu.js
  src/ec/packages/ec-component-breadcrumb-core/package.json
  src/ec/packages/ec-component-breadcrumb-harmonised/__snapshots__/breadcrumb-harmonised.test.js.snap
  src/ec/packages/ec-component-breadcrumb-harmonised/breadcrumb-harmonised.story.js
  src/ec/packages/ec-component-breadcrumb-harmonised/breadcrumb-harmonised.test.js
  src/ec/packages/ec-component-breadcrumb-harmonised/demo/data--eu.js
  src/ec/packages/ec-component-breadcrumb-harmonised/demo/data--simple--eu.js
  src/ec/packages/ec-component-breadcrumb-harmonised/package.json
  src/ec/packages/ec-component-breadcrumb-standardised/__snapshots__/breadcrumb-standardised.test.js.snap
  src/ec/packages/ec-component-breadcrumb-standardised/breadcrumb-standardised.story.js
  src/ec/packages/ec-component-breadcrumb-standardised/breadcrumb-standardised.test.js
  src/ec/packages/ec-component-breadcrumb-standardised/demo/data--eu.js
  src/ec/packages/ec-component-breadcrumb-standardised/demo/data--simple--eu.js
  src/ec/packages/ec-component-breadcrumb-standardised/package.json
  src/ec/packages/ec-component-breadcrumb/__snapshots__/breadcrumb.test.js.snap
  src/ec/packages/ec-component-breadcrumb/breadcrumb.test.js
  src/ec/packages/ec-component-breadcrumb/demo/data--eu.js
  src/ec/packages/ec-component-breadcrumb/demo/data--simple--eu.js
  src/ec/packages/ec-component-breadcrumb/ec-breadcrumb.story.js
  src/ec/packages/ec-component-breadcrumb/eu-breadcrumb.story.js
  src/ec/packages/ec-component-breadcrumb/package.json
  yarn.lock
Labels: pr: under review, tag: new feature

#498 feat(page-headers): EU adaptations, adding EU demos - FRONT-1268
  src/ec/packages/ec-component-page-header-core/adapter.js
  src/ec/packages/ec-component-page-header-core/package.json
  src/ec/packages/ec-component-page-header-core/page-header-core.story.js
  src/ec/packages/ec-component-page-header-harmonised/adapter.js
  src/ec/packages/ec-component-page-header-harmonised/package.json
  src/ec/packages/ec-component-page-header-harmonised/page-header-harmonised.story.js
  src/ec/packages/ec-component-page-header-standardised/adapter.js
  src/ec/packages/ec-component-page-header-standardised/package.json
  src/ec/packages/ec-component-page-header-standardised/page-header-standardised.story.js
  src/ec/packages/ec-component-page-header/README.md
  src/ec/packages/ec-component-page-header/__snapshots__/page-header.test.js.snap
  src/ec/packages/ec-component-page-header/adapter.js
  src/ec/packages/ec-component-page-header/demo/data--basic--eu.js
  src/ec/packages/ec-component-page-header/demo/data--branded-homepage--eu.js
  src/ec/packages/ec-component-page-header/demo/data--branded-homepage-image--eu.js
  src/ec/packages/ec-component-page-header/demo/data--events--eu.js
  src/ec/packages/ec-component-page-header/demo/data--events-description--eu.js
  src/ec/packages/ec-component-page-header/demo/data--homepage--eu.js
  src/ec/packages/ec-component-page-header/demo/data--homepage-image--eu.js
  src/ec/packages/ec-component-page-header/demo/data--title.js
  src/ec/packages/ec-component-page-header/ec-page-header.story.js
  src/ec/packages/ec-component-page-header/ecl-page-header.html.twig
  src/ec/packages/ec-component-page-header/eu-page-header.story.js
  src/ec/packages/ec-component-page-header/package.json
  src/ec/packages/ec-component-page-header/page-header.test.js
  yarn.lock
Labels: pr: modification needed, tag: new feature

#501 feat(hero-banner): Making everything optional, fixing icon knob behaviour - front-1282
  src/ec/packages/ec-component-hero-banner/hero-banner.story.js
  src/ec/packages/ec-component-hero-banner/package.json
  yarn.lock
Labels: tag: enhancement

#502 feat(language-list): Eu version - FRONT-1296
  package.json
  src/ec/packages/ec-component-language-list/language-list.story.js
  src/ec/packages/ec-component-language-list/package.json
  yarn.lock
Labels: pr: review needed, tag: enhancement

#504 fix(php): Fixing distributed php package - front-1299
  package.json
  php/php_storybook/resources/fix-build.js
  php/php_storybook/resources/get-assets.js
Labels: tag: internal

#505 feat(ecl): Updating resources to 2.31.0
  src/ec/storybook/.storybook/preview-head.html
Labels: tag: internal

#506 chore(babel): enable async/await
  babel.config.js
  package.json
  src/ec/packages/ec-component-table/table.test.js
  yarn.lock
Labels: pr: review needed, tag: internal

#508 feat(language-list): Non EU languages support added - front-1302
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-language-list.html.twig
  src/ec/packages/ec-component-language-list/README.md
  src/ec/packages/ec-component-language-list/__snapshots__/language-list.test.js.snap
  src/ec/packages/ec-component-language-list/adapter.js
  src/ec/packages/ec-component-language-list/ecl-language-list-grid.html.twig
  src/ec/packages/ec-component-language-list/ecl-language-list.html.twig
  src/ec/packages/ec-component-language-list/language-list.story.js
  src/ec/packages/ec-component-language-list/language-list.test.js
  src/ec/packages/ec-component-language-list/package.json
  src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap
  src/ec/packages/ec-component-site-header-core/adapter.js
  src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig
  src/ec/packages/ec-component-site-header-core/package.json
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/adapter.js
  src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
  src/ec/packages/ec-component-site-header-harmonised/package.json
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/adapter.js
  src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
  src/ec/packages/ec-component-site-header-standardised/package.json
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
  yarn.lock
Labels: pr: under review, tag: new feature

#507 feat(file): Adding thumbnail variant - front-1303
  src/ec/packages/ec-component-fact-figures/adapter.js
  src/ec/packages/ec-component-file/README.md
  src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
  src/ec/packages/ec-component-file/adapter.js
  src/ec/packages/ec-component-file/demo/data--thumbnail.js
  src/ec/packages/ec-component-file/ecl-file.html.twig
  src/ec/packages/ec-component-file/file.story.js
  src/ec/packages/ec-component-file/file.test.js
  src/ec/packages/ec-component-file/package.json
  yarn.lock
Labels: pr: under review, tag: new feature

#509 feat(table): Adding sortable demo - front-1304
  src/ec/packages/ec-component-table/README.md
  src/ec/packages/ec-component-table/__snapshots__/table.test.js.snap
  src/ec/packages/ec-component-table/demo/data--default.js
  src/ec/packages/ec-component-table/demo/data--multi.js
  src/ec/packages/ec-component-table/demo/data--sort-table.js
  src/ec/packages/ec-component-table/ecl-table.html.twig
  src/ec/packages/ec-component-table/package.json
  src/ec/packages/ec-component-table/table.story.js
  src/ec/packages/ec-component-table/table.test.js
  yarn.lock
Labels: pr: under review, tag: new feature

#511 fix(footer-harmonised): Fixing logo in EU for php-storybook - front-1328
  php/php_storybook/resources/fix-build.js
  src/ec/packages/ec-component-footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
  src/ec/packages/ec-component-footer-harmonised/demo/eu-data.js
  src/ec/packages/ec-component-footer-harmonised/package.json
  static/images/eu-en-desktop.svg
  static/images/eu-fr-desktop.svg
  yarn.lock
Labels: pr: under review, tag: bug fix

#510 feat(gallery): Adding footer link - front-1313
  src/ec/packages/ec-component-footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
  src/ec/packages/ec-component-gallery/README.md
  src/ec/packages/ec-component-gallery/__snapshots__/gallery.test.js.snap
  src/ec/packages/ec-component-gallery/adapter.js
  src/ec/packages/ec-component-gallery/ecl-gallery.html.twig
  src/ec/packages/ec-component-gallery/gallery.story.js
  src/ec/packages/ec-component-gallery/package.json
  utils/data-utils/src/index.js
  yarn.lock
Labels: pr: under review, tag: enhancement

#512 fix(footers): fixing logos in EU footers for php-storybook - front-1347
  src/ec/packages/ec-component-footer-core/README.md
  src/ec/packages/ec-component-footer-core/__snapshots__/footer-core.test.js.snap
  src/ec/packages/ec-component-footer-core/adapter.js
  src/ec/packages/ec-component-footer-core/demo/eu-data.js
  src/ec/packages/ec-component-footer-core/ecl-footer-core.html.twig
  src/ec/packages/ec-component-footer-harmonised/README.md
  src/ec/packages/ec-component-footer-harmonised/ecl-footer-harmonised.html.twig
  src/ec/packages/ec-component-footer-standardised/README.md
  src/ec/packages/ec-component-footer-standardised/__snapshots__/footer-standardised.test.js.snap
  src/ec/packages/ec-component-footer-standardised/adapter.js
  src/ec/packages/ec-component-footer-standardised/demo/eu-data.js
  src/ec/packages/ec-component-footer-standardised/ecl-footer-standardised.html.twig
Labels: pr: under review, tag: bug fix

#513 feat(php-storybook): Converting the php generated story files to CSF - front-1379
  php/php_storybook/resources/helpers.php
  php/php_storybook/resources/story-template.txt
  php/php_storybook/scripts/render.php
Labels: pr: review needed, tag: internal

#514 feat(scripts): Creating system aware prettier tasks for php - front-1380
  package.json
Labels: pr: review needed, tag: internal

#517 fix(favicon): Adding favicon.ico to distributed packages - front-1384
  php/php_storybook/resources/get-assets.js
  static/favicon.ico
Labels: pr: review needed, tag: bug fix
