Repository ec-europa/ecl-twig, pull requests merged in 2020-04, with the labels that each got.

#395 fix(pre-commit): Different approach for combining husky and grump-php - FRONT-960
  .gitignore
  composer.json
  docs/getting-started.md
  package.json
  scripts/grump-dis.js
  scripts/grump-dis.sh
  scripts/grump-en.js
  scripts/pre-commit.combined
  scripts/pre-commit.husky
  src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
Labels: tag: internal

#388 refactor(knobs): table optional/mandatory knobs - FRONT-924
  src/ec/packages/ec-component-table/README.md
  src/ec/packages/ec-component-table/__snapshots__/table.test.js.snap
  src/ec/packages/ec-component-table/ecl-table.html.twig
  src/ec/packages/ec-component-table/table.story.js
Labels: tag: enhancement

#392 refactor(knobs): Gallery optional/mandatory knobs -FRONT-926
  src/ec/packages/ec-component-gallery/ecl-gallery-overlay.html.twig
  src/ec/packages/ec-component-gallery/ecl-gallery.html.twig
  src/ec/packages/ec-component-gallery/gallery.story.js
Labels: pr: under review, tag: enhancement

#396 refactor(utils): tabLabels instead of buttonLabels - FRONT-962
  src/ec/packages/ec-component-accordion/accordion.story.js
  src/ec/packages/ec-component-accordion2/accordion2.story.js
  src/ec/packages/ec-component-button/button.story.js
  src/ec/packages/ec-component-checkbox/checkbox.story.js
  src/ec/packages/ec-component-datepicker/datepicker.story.js
  src/ec/packages/ec-component-file/file.story.js
  src/ec/packages/ec-component-gallery/gallery.story.js
  src/ec/packages/ec-component-hero-banner/hero-banner.story.js
  src/ec/packages/ec-component-icon/icon.story.js
  src/ec/packages/ec-component-inpage-navigation/inpage-navigation.story.js
  src/ec/packages/ec-component-language-list/language-list.story.js
  src/ec/packages/ec-component-menu/menu.story.js
  src/ec/packages/ec-component-message/message.story.js
  src/ec/packages/ec-component-page-banner/page-banner.story.js
  src/ec/packages/ec-component-radio/radio.story.js
  src/ec/packages/ec-component-search-form/search-form.story.js
  src/ec/packages/ec-component-select/select.story.js
  src/ec/packages/ec-component-site-header-core/site-header-core.story.js
  src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
  src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js
  src/ec/packages/ec-component-social-media-share/social-media-share.story.js
  src/ec/packages/ec-component-table/table.story.js
  src/ec/packages/ec-component-tag/tag.story.js
  src/ec/packages/ec-component-timeline/timeline.story.js
  utils/story-utils/src/index.js
Labels: pr: review needed, tag: internal

#398 fix(deps): Forcing version of minimalist - FRONT-1011
  package.json
  yarn.lock
Labels: tag: internal

#399 refactor(demo): Expandable, optional.mandatory knobs - FRONT-1021
  src/ec/packages/ec-component-expandable/adapter.js
  src/ec/packages/ec-component-expandable/demo/data.js
  src/ec/packages/ec-component-expandable/ecl-expandable.html.twig
  src/ec/packages/ec-component-expandable/expandable.story.js
Labels: tag: enhancement

#400 refactor(demo): File upload, optiona/mandatory knobs - FRONT-1019
  src/ec/packages/ec-component-file-upload/file-upload.story.js
  utils/story-utils/src/index.js
Labels: tag: enhancement

#401 refactor(demo): List, optional/mandatory knobs - FRONT-1020
  src/ec/packages/ec-component-description-list/description-list.story.js
  src/ec/packages/ec-component-ordered-list/ordered-list.story.js
  src/ec/packages/ec-component-unordered-list/unordered-list.story.js
Labels: tag: enhancement

#402 refactor(demo): Pagination, mandatory/optional knobs - FRONT-1018
  src/ec/packages/ec-component-pagination/pagination.story.js
Labels: pr: under review, tag: enhancement

#403 refactor(demo): Breadcrumb core, optional/mandatory knobs - FRONT-1015
  src/ec/packages/ec-component-breadcrumb-core/breadcrumb-core.story.js
  utils/story-utils/src/index.js
Labels: tag: enhancement

#404 refactor(demo): Breadcrumb standardised - optional/mandatory knobs - FRONT-1016
  src/ec/packages/ec-component-breadcrumb-standardised/breadcrumb-standardised.story.js
Labels: pr: review needed, tag: enhancement

#405 refactor(demo): Breadcrumb harmonised, optional/mandatory knobs - FRO…
  src/ec/packages/ec-component-breadcrumb-harmonised/breadcrumb-harmonised.story.js
Labels: pr: review needed, tag: enhancement

#406 feat(form-elements): Refactoring form elements components - FRONT-1029
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-checkbox/__snapshots__/checkbox.test.js.snap
  src/ec/packages/ec-component-checkbox/checkbox.story.js
  src/ec/packages/ec-component-checkbox/ecl-checkbox-button.html.twig
  src/ec/packages/ec-component-checkbox/ecl-checkbox-group.html.twig
  src/ec/packages/ec-component-checkbox/package.json
  src/ec/packages/ec-component-expandable/__snapshots__/expandable.test.js.snap
  src/ec/packages/ec-component-file-upload/__snapshots__/file-upload.test.js.snap
  src/ec/packages/ec-component-file-upload/ecl-file-upload.html.twig
  src/ec/packages/ec-component-file-upload/package.json
  src/ec/packages/ec-component-radio/__snapshots__/radio.test.js.snap
  src/ec/packages/ec-component-radio/ecl-radio-button.html.twig
  src/ec/packages/ec-component-radio/ecl-radio-group.html.twig
  src/ec/packages/ec-component-radio/package.json
  src/ec/packages/ec-component-radio/radio.story.js
  src/ec/packages/ec-component-search-form/__snapshots__/search-form.test.js.snap
  src/ec/packages/ec-component-search-form/package.json
  src/ec/packages/ec-component-select/__snapshots__/select.test.js.snap
  src/ec/packages/ec-component-select/ecl-select.html.twig
  src/ec/packages/ec-component-select/package.json
  src/ec/packages/ec-component-select/select.story.js
  src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
  src/ec/packages/ec-component-text-area/__snapshots__/text-area.test.js.snap
  src/ec/packages/ec-component-text-area/ecl-text-area.html.twig
  src/ec/packages/ec-component-text-area/package.json
  src/ec/packages/ec-component-text-input/__snapshots__/text-input.test.js.snap
  src/ec/packages/ec-component-text-input/ecl-text-input.html.twig
  src/ec/packages/ec-component-text-input/package.json
  utils/story-utils/src/index.js
  yarn.lock
Labels: pr: under review, tag: enhancement

#432 feat(ecl-compliance): Radio, adding child template - FRONT-1069
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-form-group.html.twig
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-radio.html.twig
  src/ec/packages/ec-component-radio/README.md
  src/ec/packages/ec-component-radio/__snapshots__/radio.test.js.snap
  src/ec/packages/ec-component-radio/ecl-radio-button.html.twig
  src/ec/packages/ec-component-radio/ecl-radio-group.html.twig
  src/ec/packages/ec-component-radio/radio.story.js
  src/ec/packages/ec-component-radio/radio.test.js
Labels: pr: under review, tag: new feature

#434 feat(ecl-compliance): Expandable, adding child template - FRONT-1071
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-expandable.html.twig
  src/ec/packages/ec-component-expandable/README.md
  src/ec/packages/ec-component-expandable/__snapshots__/expandable.test.js.snap
  src/ec/packages/ec-component-expandable/ecl-expandable.html.twig
  src/ec/packages/ec-component-expandable/expandable.test.js
Labels: tag: new feature

#411 feat(ecl-compliance): Breadcrumb, adding child template, adding optional/mandatory knobs - FRONT-1103
  src/ec/packages/ec-component-breadcrumb/__snapshots__/breadcrumb.test.js.snap
  src/ec/packages/ec-component-breadcrumb/breadcrumb.story.js
  src/ec/packages/ec-component-breadcrumb/breadcrumb.test.js
  src/ec/packages/ec-component-breadcrumb/ecl-breadcrumb.html.twig
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-breadcrumb.html.twig
Labels: pr: under review, tag: new feature

#412 feat(ecl-compliance): Search form, adding child template - FRONT-1072
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-search-form.html.twig
  src/ec/packages/ec-component-search-form/__snapshots__/search-form.test.js.snap
  src/ec/packages/ec-component-search-form/ecl-search-form.html.twig
  src/ec/packages/ec-component-search-form/search-form.story.js
  src/ec/packages/ec-component-search-form/search-form.test.js
Labels: pr: under review, tag: new feature

#413 feat(ecl-compliance): Fact and figures, adding child template - FRONT-1077
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-fact-figures.html.twig
  src/ec/packages/ec-component-fact-figures/__snapshots__/fact-figures.test.js.snap
  src/ec/packages/ec-component-fact-figures/ecl-fact-figures.html.twig
  src/ec/packages/ec-component-fact-figures/fact-figures.story.js
  src/ec/packages/ec-component-fact-figures/fact-figures.test.js
Labels: pr: under review, tag: new feature

#409 feat(ecl-compliance): Button, adding child template - FRONT-1054
  src/ec/packages/ec-component-button/__snapshots__/button.test.js.snap
  src/ec/packages/ec-component-button/button.story.js
  src/ec/packages/ec-component-button/button.test.js
  src/ec/packages/ec-component-button/ecl-button.html.twig
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-button.html.twig
  src/ec/packages/ec-component-ecl-compliance/package.json
Labels: pr: review needed, tag: new feature

#415 feat(ecl-compliance): Blockquote, adding child template - FRONT-1053
  src/ec/packages/ec-component-blockquote/__snapshots__/blockquote.test.js.snap
  src/ec/packages/ec-component-blockquote/blockquote.story.js
  src/ec/packages/ec-component-blockquote/blockquote.test.js
  src/ec/packages/ec-component-blockquote/ecl-blockquote.html.twig
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-blockquote.html.twig
Labels: pr: review needed, tag: new feature

#440 feat(page-header): Adding background-image variant
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-page-header/README.md
  src/ec/packages/ec-component-page-header/__snapshots__/page-header.test.js.snap
  src/ec/packages/ec-component-page-header/adapter.js
  src/ec/packages/ec-component-page-header/demo/data--background-image.js
  src/ec/packages/ec-component-page-header/ecl-page-header.html.twig
  src/ec/packages/ec-component-page-header/package.json
  src/ec/packages/ec-component-page-header/page-header.story.js
  src/ec/packages/ec-component-page-header/page-header.test.js
  yarn.lock
Labels: pr: under review, tag: new feature

#439 feat(label): Adding component, FRONT-1131
  src/ec/packages/ec-component-label/.npmignore
  src/ec/packages/ec-component-label/README.md
  src/ec/packages/ec-component-label/__snapshots__/label.test.js.snap
  src/ec/packages/ec-component-label/ecl-label.html.twig
  src/ec/packages/ec-component-label/label.story.js
  src/ec/packages/ec-component-label/label.test.js
  src/ec/packages/ec-component-label/package.json
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: under review, tag: new feature
