Repository ec-europa/ecl-twig, pull requests merged in 2020-02, with the labels that each got.

#315 fix(php-storybook): datepicker is in the form section - TWIG-256
  php/php_storybook/resources/helpers.php
Labels: pr: review needed

#320 chore(changelog): add lerna-changelog - FRONT-376
  .github/CONTRIBUTING.md
  package.json
  yarn.lock
Labels: pr: questions

#324 feat(knobs): Quick order change knobs blockquote - FRONT-458
  src/ec/packages/ec-component-blockquote/blockquote.story.js
Labels: pr: under review

#327 fix(file-input): Updating component to 2.22.1 - FRONT-465
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-file-upload/README.md
  src/ec/packages/ec-component-file-upload/__snapshots__/file-upload.test.js.snap
  src/ec/packages/ec-component-file-upload/adapter.js
  src/ec/packages/ec-component-file-upload/demo/data--multiple.js
  src/ec/packages/ec-component-file-upload/demo/data.js
  src/ec/packages/ec-component-file-upload/ecl-file-upload.html.twig
  src/ec/packages/ec-component-file-upload/file-upload.story.js
  src/ec/packages/ec-component-file-upload/package.json
  yarn.lock
Labels: pr: under review

#313 feat(php-storybook): Integration with the CI environment
  .drone.yml
  package.json
  php/.storybook/webpack.config.js
  scripts/set-netlify-deployment-status.js
  yarn.lock
Labels: pr: review needed, tag: internal

#323 feat(knobs): update banner hero/page component - FRONT-457
  src/ec/packages/ec-component-hero-banner/hero-banner.story.js
  src/ec/packages/ec-component-page-banner/page-banner.story.js
Labels: tag: enhancement

#317 internal: changelog - Applying ECL schema - TWIG-255
  .gitignore
  docs/README.md
  docs/conventions.md
  docs/release.md
  lerna.json
  package.json
  yarn.lock
Labels: pr: under review, tag: internal

#321 feat(knobs): update file component - TWIG-342
  src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
  src/ec/packages/ec-component-file/ecl-file.html.twig
  src/ec/packages/ec-component-file/file.story.js
Labels: tag: enhancement

#326 feat(knobs): Update knobs datepicker - FRONT-461
  src/ec/packages/ec-component-datepicker/datepicker.story.js
  src/ec/packages/ec-component-datepicker/ecl-datepicker.html.twig
Labels: tag: enhancement

#322 feat(knobs): update fact-figures component - FRONT-450
  src/ec/packages/ec-component-fact-figures/README.md
  src/ec/packages/ec-component-fact-figures/adapter.js
  src/ec/packages/ec-component-fact-figures/ecl-fact-figures.html.twig
  src/ec/packages/ec-component-fact-figures/fact-figures.story.js
Labels: pr: review needed, tag: enhancement

#325 feat(knobs): Button - FRONT-459
  src/ec/packages/ec-component-button/README.md
  src/ec/packages/ec-component-button/button.story.js
Labels: pr: under review, tag: enhancement

#328 fix(php-storybook): English logo fixed - FRONT-484
  php/php_storybook/resources/fix-build.js
Labels: tag: bug fix

#332 fix(deps): Removing shellcheck - FRONT-493
  package.json
  yarn.lock
Labels: pr: review needed, tag: internal

#331 refactor(knobs): in page navigation, adding buttons as in ECL - FRONT-486
  src/ec/packages/ec-component-inpage-navigation/inpage-navigation.story.js
  src/ec/packages/ec-component-inpage-navigation/package.json
  yarn.lock
Labels: tag: enhancement

#333 fix(link): Fixing cta story knobs - FRONT-487
  src/ec/packages/ec-component-link/link.story.js
Labels: tag: bug fix

#336 feat(Pagination): added knob Aria label - FRONT-488
  src/ec/packages/ec-component-pagination/pagination.story.js
Labels: pr: review needed, tag: enhancement

#337 refactor(skip-link): Added knob, using specs in story and tests, tests updated - FRONT-489
  src/ec/packages/ec-component-skip-link/README.md
  src/ec/packages/ec-component-skip-link/__snapshots__/skip-link.test.js.snap
  src/ec/packages/ec-component-skip-link/skip-link.story.js
  src/ec/packages/ec-component-skip-link/skip-link.test.js
Labels: pr: under review, tag: enhancement

#318 feat(card): Improve knobs on component- TWIG-254
  src/ec/packages/ec-component-card/adapter.js
  src/ec/packages/ec-component-card/card.story.js
  src/ec/packages/ec-component-card/ecl-card.html.twig
Labels: tag: enhancement

#329 feat(site-headers): Adding buttons to show/hide login and language switcher where needed - FRONT-485
  src/ec/packages/ec-component-site-header-core/site-header-core.story.js
  src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
  src/ec/packages/ec-component-site-header/ecl-site-header.html.twig
  src/ec/packages/ec-component-site-header/site-header.story.js
Labels: pr: review needed, tag: enhancement

#335 feat(language-list): make the overlay knob work in 1 template - FRONT-491
  src/ec/packages/ec-component-language-list/README.md
  src/ec/packages/ec-component-language-list/ecl-language-list-main.html.twig
  src/ec/packages/ec-component-language-list/ecl-language-list-overlay.html.twig
  src/ec/packages/ec-component-language-list/ecl-language-list-splash.html.twig
  src/ec/packages/ec-component-language-list/language-list.story.js
  src/ec/packages/ec-component-language-list/language-list.test.js
  src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap
  src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
  src/ec/packages/ec-component-site-header/ecl-site-header.html.twig
Labels: pr: review needed, tag: enhancement

#334 feat(tag): Improve knobs on component - FRONT-492
  src/ec/packages/ec-component-tag/tag.story.js
Labels: pr: questions, tag: enhancement

#339 feat(knobs): Poc for a panel with three sub-panels, buttons for show/hiding - FRONT-813
  src/ec/packages/ec-component-card/__snapshots__/card.test.js.snap
  src/ec/packages/ec-component-card/card.story.js
  src/ec/packages/ec-component-card/ecl-card.html.twig
Labels: pr: under review, tag: new feature

#343 fix(language-list): Renaming main template, fixing php-storybook, fixing template syntax - FRONT-823
  php/php_storybook/scripts/render.js
  php/php_storybook/scripts/render.php
  src/ec/packages/ec-component-card/ecl-card.html.twig
  src/ec/packages/ec-component-language-list/README.md
  src/ec/packages/ec-component-language-list/ecl-language-list-grid.html.twig
  src/ec/packages/ec-component-language-list/ecl-language-list-main.html.twig
  src/ec/packages/ec-component-language-list/ecl-language-list.html.twig
  src/ec/packages/ec-component-language-list/language-list.story.js
  src/ec/packages/ec-component-language-list/language-list.test.js
  src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig
  src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
  src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
  src/ec/packages/ec-component-site-header/ecl-site-header.html.twig
Labels: pr: review needed, tag: breaking change
