Repository ec-europa/ecl-twig, pull requests merged in 2020-01, with the labels that each got.

#275 fix(menu): href attribute needs quotes - TWIG-187
  src/ec/packages/ec-component-menu/ecl-menu.html.twig
Labels: pr: under review

#276 fix(deps): Updating some deps, using resolutions block to get rid of duplicated version of istanbul-reports
  package.json
  yarn.lock
Labels: pr: under review

#259 feat(php-storybook): Configuring static version, creating script for deploying to gh pages - TWIG-158
  .eslintrc.js
  .gitignore
  docs/getting-started.md
  package.json
  php/php_storybook/resources/fix-build.js
  php/php_storybook/resources/get-assets.js
  src/ec/packages/ec-component-icon/__snapshots__/icon.test.js.snap
  src/ec/packages/ec-component-icon/demo/data--audio.js
  src/ec/packages/ec-component-icon/demo/data--facebook.js
  src/ec/packages/ec-component-icon/demo/data--success.js
  yarn.lock
Labels: pr: modification needed

#281 feat(footer-harmonised): Adding group3 - TWIG-202
  src/ec/.storybook/preview-head.html
  src/ec/packages/ec-component-footer-harmonised/README.md
  src/ec/packages/ec-component-footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
  src/ec/packages/ec-component-footer-harmonised/demo/data--group3.js
  src/ec/packages/ec-component-footer-harmonised/ecl-footer-harmonised.html.twig
  src/ec/packages/ec-component-footer-harmonised/footer-harmonised.story.js
  src/ec/packages/ec-component-footer-harmonised/footer-harmonised.test.js
  src/ec/packages/ec-component-footer-harmonised/package.json
  yarn.lock
Labels: pr: under review

#282 fix(site-headers): Icons size reviewed - TWIG-201
  php/php_storybook/composer.json
  php/php_storybook/package.json
  src/ec/packages/ec-component-footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap
  src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
Labels: pr: under review

#270 feat(ecl-diff): Adding command to diff a component against the ECL markup - TWIG-180
  docs/getting-started.md
  package.json
  php/php_storybook/scripts/diff.js
  php/php_storybook/scripts/ecl-diff.js
  src/ec/packages/ec-component-menu/__snapshots__/menu.test.js.snap
  src/ec/packages/ec-component-menu/ecl-menu.html.twig
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  yarn.lock
Labels: pr: modification needed

#277 fix(drone): Attempt to update the status in case of failure in each build step - TWIG-189
  .drone.yml
  .eslintignore
  scripts/failcheck.js
  scripts/set-netlify-deployment-status.js
Labels: pr: under review

#285 fix(ecl-diff): regex improved, other fixes - TWIG-206
  php/php_storybook/scripts/ecl-diff.js
Labels: pr: under review

#286 feat(ecl-diff): Adding the possibility of diffing a specific version of the ECL components - TWIG-219
  php/php_storybook/scripts/ecl-diff.js
Labels: pr: under review

#289 fix(storybook): add babel-polyfill to preview-head for IE Edge - TWIG-220
  src/ec/.storybook/preview-head.html
Labels: pr: questions, pr: review needed

#295 fix(ecl-diff): Browsing Ecl website with puppeteer - TWIG-235
  php/php_storybook/scripts/ecl-diff.js
Labels: pr: review needed

#290 fix(php-storybook): fixing grouping issues in the story files - TWIG-221
  php/php_storybook/resources/helpers.php
Labels: pr: review needed

#300 feat(text-area): making diff match - TWIG-241
  src/ec/packages/ec-component-text-area/__snapshots__/text-area.test.js.snap
  src/ec/packages/ec-component-text-area/adapter.js
  src/ec/packages/ec-component-text-area/ecl-text-area.html.twig
  src/ec/packages/ec-component-text-area/text-area.story.js
Labels: pr: under review

#296 feat(checkbox): Green diff with ECL - TWIG-225
  src/ec/packages/ec-component-checkbox/__snapshots__/checkbox.test.js.snap
  src/ec/packages/ec-component-checkbox/adapter.js
  src/ec/packages/ec-component-checkbox/checkbox.story.js
  src/ec/packages/ec-component-checkbox/ecl-checkbox-button.html.twig
  src/ec/packages/ec-component-checkbox/ecl-checkbox-group.html.twig
Labels: pr: under review

#299 feat(text-input): Green diff with ECL - TWIG-242
  src/ec/packages/ec-component-text-input/__snapshots__/text-input.test.js.snap
  src/ec/packages/ec-component-text-input/adapter.js
  src/ec/packages/ec-component-text-input/ecl-text-input.html.twig
  src/ec/packages/ec-component-text-input/text-input.story.js
Labels: pr: under review

#301 feat(search-form): (almost) green diff with ECL - TWIG-238
  src/ec/packages/ec-component-button/ecl-button.html.twig
  src/ec/packages/ec-component-search-form/__snapshots__/search-form.test.js.snap
  src/ec/packages/ec-component-search-form/demo/data.js
  src/ec/packages/ec-component-search-form/search-form.test.js
Labels: pr: under review

#302 feat(breadcrumb-harmonised): component review - TWIG-223
  src/ec/.storybook/config.js
  src/ec/packages/ec-component-breadcrumb-harmonised/adapter.js
  src/ec/packages/ec-component-breadcrumb-harmonised/breadcrumb-harmonised.story.js
  src/ec/packages/ec-component-breadcrumb-harmonised/breadcrumb-harmonised.test.js
  src/ec/packages/ec-component-page-header-harmonised/__snapshots__/page-header-harmonised.test.js.snap
Labels: pr: under review

#303 feat(breadcrumb-core): Component review - TWIG-222
  src/ec/packages/ec-component-breadcrumb-core/adapter.js
  src/ec/packages/ec-component-breadcrumb-core/breadcrumb-core.story.js
  src/ec/packages/ec-component-breadcrumb-core/breadcrumb-core.test.js
  src/ec/packages/ec-component-page-header-core/__snapshots__/page-header-core.test.js.snap
Labels: pr: under review

#304 feat(social-media-share): Green diff with ECL - TWIG-243
  src/ec/packages/ec-component-social-media-share/__snapshots__/social-media-share.test.js.snap
  src/ec/packages/ec-component-social-media-share/demo/data.js
Labels: pr: review needed

#297 feat(select): (almost) green diff with ECL - TWIG-240
  src/ec/packages/ec-component-select/__snapshots__/select.test.js.snap
  src/ec/packages/ec-component-select/demo/data.js
  src/ec/packages/ec-component-select/ecl-select.html.twig
  src/ec/packages/ec-component-select/select.story.js
  src/ec/packages/ec-component-select/select.test.js
Labels: pr: under review

#298 feat(radio): Green diff with ECL (default and binary) - TWIG-239
  src/ec/packages/ec-component-radio/__snapshots__/radio.test.js.snap
  src/ec/packages/ec-component-radio/adapter.js
  src/ec/packages/ec-component-radio/ecl-radio-button.html.twig
  src/ec/packages/ec-component-radio/radio.story.js
Labels: pr: under review

#309 feat(storybook): Showing site-header-harmonised, site-header-standardised and menu - TWIG-248
  src/ec/packages/ec-component-menu/__snapshots__/menu.test.js.snap
  src/ec/packages/ec-component-menu/menu.story.js
  src/ec/packages/ec-component-menu/package.json
  src/ec/packages/ec-component-site-header-harmonised/package.json
  src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/package.json
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
  yarn.lock
Labels: pr: under review

#310 feat(footer): Using both spec files, green ECL diff - TWIG-249
  src/ec/packages/ec-component-footer/adapter.js
  src/ec/packages/ec-component-footer/demo/data--corporate.js
  src/ec/packages/ec-component-footer/demo/data--custom.js
  src/ec/packages/ec-component-footer/demo/data.js
  src/ec/packages/ec-component-footer/footer.story.js
  src/ec/packages/ec-component-footer/footer.test.js
Labels: pr: under review

#311 feat(ecl-diff): Adaptations for ECL 2.22.0 - TWIG-250
  php/php_storybook/scripts/ecl-diff.js
Labels: pr: under review

#308 feat(datepicker): Adding component - TWIG-247
  src/ec/packages/ec-component-datepicker/.npmignore
  src/ec/packages/ec-component-datepicker/README.md
  src/ec/packages/ec-component-datepicker/__snapshots__/datepicker.test.js.snap
  src/ec/packages/ec-component-datepicker/adapter.js
  src/ec/packages/ec-component-datepicker/datepicker.story.js
  src/ec/packages/ec-component-datepicker/datepicker.test.js
  src/ec/packages/ec-component-datepicker/demo/data.js
  src/ec/packages/ec-component-datepicker/ecl-datepicker.html.twig
  src/ec/packages/ec-component-datepicker/package.json
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: pr: modification needed
