Repository ec-europa/ecl-twig, pull requests merged in 2020-05, with the labels that each got.

#416 feat(ecl-compliance): Breadcrumb core, adding child template - FRONT-1104
  src/ec/packages/ec-component-breadcrumb-core/README.md
  src/ec/packages/ec-component-breadcrumb-core/__snapshots__/breadcrumb-core.test.js.snap
  src/ec/packages/ec-component-breadcrumb-core/breadcrumb-core.story.js
  src/ec/packages/ec-component-breadcrumb-core/breadcrumb-core.test.js
  src/ec/packages/ec-component-breadcrumb-core/ecl-breadcrumb-core.html.twig
  src/ec/packages/ec-component-ecl-compliance/package.json
  yarn.lock
Labels: pr: review needed, tag: new feature

#446 fix(card): Adding checks on props - FRONT-1138
  src/ec/packages/ec-component-card/ecl-card.html.twig
Labels: pr: review needed

#451 fix(language-list): Adding checks for props - FRONT-1143
  src/ec/packages/ec-component-language-list/README.md
  src/ec/packages/ec-component-language-list/ecl-language-list-grid.html.twig
  src/ec/packages/ec-component-language-list/ecl-language-list-item.html.twig
  src/ec/packages/ec-component-language-list/ecl-language-list.html.twig
Labels: pr: review needed

#447 fix(button): Using local variable _disabled - FRONT-1139
  src/ec/packages/ec-component-button/ecl-button.html.twig
Labels: pr: review needed, tag: bug fix

#449 fix(radio): Initializing local _extra_attributes variable - FRONT-1144
  src/ec/packages/ec-component-radio/ecl-radio-button.html.twig
Labels: tag: bug fix

#448 fix(menu): using local variables - FRONT-1140
  src/ec/packages/ec-component-menu/__snapshots__/menu.test.js.snap
  src/ec/packages/ec-component-menu/ecl-menu.html.twig
Labels: tag: bug fix

#419 feat(ecl-compliance): Social Media Follow, adding child template - FRONT-1094
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-icon.html.twig
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-social-media.html.twig
  src/ec/packages/ec-component-icon/__snapshots__/icon.test.js.snap
  src/ec/packages/ec-component-link/__snapshots__/link.test.js.snap
  src/ec/packages/ec-component-social-media-follow/README.md
  src/ec/packages/ec-component-social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/ec/packages/ec-component-social-media-follow/ecl-social-media-follow.html.twig
  src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js
  src/ec/packages/ec-component-social-media-follow/social-media-follow.test.js
Labels: pr: review needed, tag: new feature

#450 fix(gallery): Adding checks for props - FRONT-1141
  src/ec/packages/ec-component-gallery/__snapshots__/gallery.test.js.snap
  src/ec/packages/ec-component-gallery/ecl-gallery-item.html.twig
  src/ec/packages/ec-component-gallery/ecl-gallery-overlay.html.twig
  src/ec/packages/ec-component-gallery/ecl-gallery.html.twig
Labels: tag: enhancement

#453 chore(eslint): fix linting rules - noissue
  .eslintrc.js
  src/ec/packages/ec-component-accordion/accordion.story.js
  src/ec/packages/ec-component-accordion/accordion.test.js
  src/ec/packages/ec-component-accordion2/accordion2.story.js
  src/ec/packages/ec-component-accordion2/accordion2.test.js
  src/ec/packages/ec-component-blockquote/blockquote.story.js
  src/ec/packages/ec-component-breadcrumb-core/breadcrumb-core.story.js
  src/ec/packages/ec-component-breadcrumb-harmonised/breadcrumb-harmonised.story.js
  src/ec/packages/ec-component-breadcrumb-standardised/breadcrumb-standardised.story.js
  src/ec/packages/ec-component-button/button.story.js
  src/ec/packages/ec-component-card/card.story.js
  src/ec/packages/ec-component-checkbox/checkbox.story.js
  src/ec/packages/ec-component-contextual-navigation/contextual-navigation.story.js
  src/ec/packages/ec-component-date-block/date-block.story.js
  src/ec/packages/ec-component-date-block/date-block.test.js
  src/ec/packages/ec-component-datepicker/datepicker.story.js
  src/ec/packages/ec-component-datepicker/datepicker.test.js
  src/ec/packages/ec-component-description-list/description-list.story.js
  src/ec/packages/ec-component-expandable/expandable.story.js
  src/ec/packages/ec-component-fact-figures/fact-figures.story.js
  src/ec/packages/ec-component-file-upload/file-upload.story.js
  src/ec/packages/ec-component-file/file.story.js
  src/ec/packages/ec-component-footer-core/footer-core.story.js
  src/ec/packages/ec-component-footer-harmonised/footer-harmonised.story.js
  src/ec/packages/ec-component-footer-standardised/footer-standardised.story.js
  src/ec/packages/ec-component-gallery/gallery.story.js
  src/ec/packages/ec-component-hero-banner/hero-banner.story.js
  src/ec/packages/ec-component-inpage-navigation/inpage-navigation.story.js
  src/ec/packages/ec-component-inpage-navigation/inpage-navigation.test.js
  src/ec/packages/ec-component-language-list/language-list.story.js
  src/ec/packages/ec-component-link/link.story.js
  src/ec/packages/ec-component-media-container/media-container.story.js
  src/ec/packages/ec-component-menu-legacy/menu-legacy.test.js
  src/ec/packages/ec-component-menu/menu.story.js
  src/ec/packages/ec-component-message/message.story.js
  src/ec/packages/ec-component-ordered-list/ordered-list.story.js
  src/ec/packages/ec-component-page-banner/page-banner.story.js
  src/ec/packages/ec-component-page-header-core/page-header-core.story.js
  src/ec/packages/ec-component-page-header-harmonised/page-header-harmonised.story.js
  src/ec/packages/ec-component-page-header-standardised/page-header-standardised.story.js
  src/ec/packages/ec-component-page-header/adapter.js
  src/ec/packages/ec-component-page-header/page-header.story.js
  src/ec/packages/ec-component-pagination/pagination.story.js
  src/ec/packages/ec-component-radio/radio.story.js
  src/ec/packages/ec-component-search-form/search-form.story.js
  src/ec/packages/ec-component-select/select.story.js
  src/ec/packages/ec-component-site-header-core/site-header-core.story.js
  src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
  src/ec/packages/ec-component-site-header/site-header.story.js
  src/ec/packages/ec-component-skip-link/skip-link.story.js
  src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js
  src/ec/packages/ec-component-social-media-share/social-media-share.story.js
  src/ec/packages/ec-component-table/table.story.js
  src/ec/packages/ec-component-tag/tag.story.js
  src/ec/packages/ec-component-text-area/text-area.story.js
  src/ec/packages/ec-component-text-input/text-input.story.js
  src/ec/packages/ec-component-timeline/timeline.story.js
  src/ec/packages/ec-component-timeline/timeline.test.js
  src/ec/packages/ec-component-unordered-list/unordered-list.story.js
Labels: tag: internal

#421 feat(ecl-compliance): Accordion, adding child template - FRONT-1051
  src/ec/packages/ec-component-accordion/README.md
  src/ec/packages/ec-component-accordion/__snapshots__/accordion.test.js.snap
  src/ec/packages/ec-component-accordion/accordion.story.js
  src/ec/packages/ec-component-accordion/accordion.test.js
  src/ec/packages/ec-component-accordion/ecl-accordion.html.twig
  src/ec/packages/ec-component-breadcrumb-core/__snapshots__/breadcrumb-core.test.js.snap
  src/ec/packages/ec-component-breadcrumb-harmonised/__snapshots__/breadcrumb-harmonised.test.js.snap
  src/ec/packages/ec-component-breadcrumb-standardised/__snapshots__/breadcrumb-standardised.test.js.snap
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-accordion.html.twig
Labels: pr: review needed, tag: new feature

#423 feat(ecl-compliance): Media Container, adding child template - FRONT-1096
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-media-container.html.twig
  src/ec/packages/ec-component-media-container/README.md
  src/ec/packages/ec-component-media-container/__snapshots__/media-container.test.js.snap
  src/ec/packages/ec-component-media-container/ecl-media-container.html.twig
  src/ec/packages/ec-component-media-container/media-container.story.js
  src/ec/packages/ec-component-media-container/media-container.test.js
Labels: pr: review needed, tag: new feature

#424 feat(ecl-compliance): Pagination, adding child template - FRONT-1097
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-pagination.html.twig
  src/ec/packages/ec-component-pagination/README.md
  src/ec/packages/ec-component-pagination/__snapshots__/pagination.test.js.snap
  src/ec/packages/ec-component-pagination/ecl-pagination.html.twig
  src/ec/packages/ec-component-pagination/pagination.story.js
  src/ec/packages/ec-component-pagination/pagination.test.js
Labels: pr: under review, tag: new feature

#425 feat(ecl-compliance): Skip link, adding child template - FRONT-1107
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-skip-link.html.twig
  src/ec/packages/ec-component-skip-link/README.md
  src/ec/packages/ec-component-skip-link/__snapshots__/skip-link.test.js.snap
  src/ec/packages/ec-component-skip-link/ecl-skip-link.html.twig
  src/ec/packages/ec-component-skip-link/skip-link.story.js
  src/ec/packages/ec-component-skip-link/skip-link.test.js
Labels: pr: review needed, tag: new feature

#426 feat(ecl-compliance): Date Block, adding child template - FRONT-1062
  src/ec/packages/ec-component-date-block/__snapshots__/date-block.test.js.snap
  src/ec/packages/ec-component-date-block/date-block.story.js
  src/ec/packages/ec-component-date-block/date-block.test.js
  src/ec/packages/ec-component-date-block/ecl-date-block.html.twig
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-date-block.html.twig
Labels: pr: under review, tag: new feature

#427 feat(ecl-compliance): Tag, adding child template - FRONT-1076
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-tag.html.twig
  src/ec/packages/ec-component-tag/README.md
  src/ec/packages/ec-component-tag/__snapshots__/tag.test.js.snap
  src/ec/packages/ec-component-tag/ecl-tag.html.twig
  src/ec/packages/ec-component-tag/tag.story.js
  src/ec/packages/ec-component-tag/tag.test.js
Labels: pr: review needed, tag: new feature

#430 feat(ecl-compliance): File, adding child template - FRONT-1074
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-file.html.twig
  src/ec/packages/ec-component-file/README.md
  src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
  src/ec/packages/ec-component-file/ecl-file.html.twig
  src/ec/packages/ec-component-file/file.story.js
  src/ec/packages/ec-component-file/file.test.js
Labels: pr: review needed, tag: new feature

#431 feat(ecl-compliance): Language list, adding child template - FRONT-1065
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-language-list.html.twig
  src/ec/packages/ec-component-language-list/README.md
  src/ec/packages/ec-component-language-list/__snapshots__/language-list.test.js.snap
  src/ec/packages/ec-component-language-list/ecl-language-list-grid.html.twig
  src/ec/packages/ec-component-language-list/ecl-language-list-item.html.twig
  src/ec/packages/ec-component-language-list/ecl-language-list.html.twig
  src/ec/packages/ec-component-language-list/language-list.story.js
  src/ec/packages/ec-component-language-list/language-list.test.js
Labels: pr: review needed, tag: new feature

#433 feat(ecl-compliance): File upload, adding child template - FRONT-1070
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-file-upload.html.twig
  src/ec/packages/ec-component-file-upload/README.md
  src/ec/packages/ec-component-file-upload/__snapshots__/file-upload.test.js.snap
  src/ec/packages/ec-component-file-upload/ecl-file-upload.html.twig
  src/ec/packages/ec-component-file-upload/file-upload.story.js
  src/ec/packages/ec-component-file-upload/file-upload.test.js
Labels: pr: review needed, tag: new feature

#438 feat(ecl-compliance): Ordered list, adding child template - FRONT-1099
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-ordered-list.html.twig
  src/ec/packages/ec-component-ordered-list/README.md
  src/ec/packages/ec-component-ordered-list/__snapshots__/ordered-list.test.js.snap
  src/ec/packages/ec-component-ordered-list/ecl-ordered-list.html.twig
  src/ec/packages/ec-component-ordered-list/ordered-list.story.js
  src/ec/packages/ec-component-ordered-list/ordered-list.test.js
Labels: pr: review needed, tag: new feature

#435 feat(ecl-compliance): Card, adding child template - FRONT-1058
  src/ec/packages/ec-component-card/README.md
  src/ec/packages/ec-component-card/__snapshots__/card.test.js.snap
  src/ec/packages/ec-component-card/adapter.js
  src/ec/packages/ec-component-card/card.story.js
  src/ec/packages/ec-component-card/card.test.js
  src/ec/packages/ec-component-card/ecl-card.html.twig
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-card.html.twig
Labels: pr: review needed, tag: new feature

#436 feat(ecl-compliance): Hero Banner, adding child template - FRONT-1080
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-hero-banner.html.twig
  src/ec/packages/ec-component-hero-banner/README.md
  src/ec/packages/ec-component-hero-banner/__snapshots__/hero-banner.test.js.snap
  src/ec/packages/ec-component-hero-banner/ecl-hero-banner.html.twig
  src/ec/packages/ec-component-hero-banner/hero-banner.story.js
  src/ec/packages/ec-component-hero-banner/hero-banner.test.js
Labels: pr: review needed, tag: new feature

#441 feat(ecl-compliance): Table, adding child template - FRONT-1078
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-table.html.twig
  src/ec/packages/ec-component-table/README.md
  src/ec/packages/ec-component-table/__snapshots__/table.test.js.snap
  src/ec/packages/ec-component-table/ecl-table.html.twig
  src/ec/packages/ec-component-table/table.story.js
  src/ec/packages/ec-component-table/table.test.js
Labels: pr: review needed, tag: new feature

#437 feat(ecl-compliance): Page Banner, show/hide buttons, adding child template - FRONT-1081
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-page-banner.html.twig
  src/ec/packages/ec-component-page-banner/__snapshots__/page-banner.test.js.snap
  src/ec/packages/ec-component-page-banner/ecl-page-banner.html.twig
  src/ec/packages/ec-component-page-banner/page-banner.story.js
  src/ec/packages/ec-component-page-banner/page-banner.test.js
Labels: pr: review needed, tag: new feature

#442 feat(ecl-compliance): Description list, adding child template - FRONT-1100
  src/ec/packages/ec-component-description-list/README.md
  src/ec/packages/ec-component-description-list/__snapshots__/description-list.test.js.snap
  src/ec/packages/ec-component-description-list/description-list.story.js
  src/ec/packages/ec-component-description-list/description-list.test.js
  src/ec/packages/ec-component-description-list/ecl-description-list.html.twig
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-description-list.html.twig
Labels: tag: new feature

#443 feat(ecl-compliance): Unordered list, adding child template - FRONT-1098
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-unordered-list.html.twig
  src/ec/packages/ec-component-unordered-list/README.md
  src/ec/packages/ec-component-unordered-list/__snapshots__/unordered-list.test.js.snap
  src/ec/packages/ec-component-unordered-list/ecl-unordered-list.html.twig
  src/ec/packages/ec-component-unordered-list/unordered-list.story.js
  src/ec/packages/ec-component-unordered-list/unordered-list.test.js
Labels: pr: review needed, tag: new feature

#444 feat(ecl-compliance): Site Header Core, adding child template - FRONT-1090
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-site-header-core.html.twig
  src/ec/packages/ec-component-site-header-core/README.md
  src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap
  src/ec/packages/ec-component-site-header-core/adapter.js
  src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig
  src/ec/packages/ec-component-site-header-core/site-header-core.story.js
  src/ec/packages/ec-component-site-header-core/site-header-core.test.js
Labels: tag: new feature

#452 feat(ecl-compliance): Site Header Standardised, adding child template - FRONT-1091
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-site-header-standardised.html.twig
  src/ec/packages/ec-component-site-header-standardised/README.md
  src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/ec/packages/ec-component-site-header-standardised/adapter.js
  src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
  src/ec/packages/ec-component-site-header-standardised/site-header-standardised.test.js
Labels: tag: new feature

#456 feat(ecl-compliance): Page Header Standardised - FRONT-1088
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-page-header-standardised.html.twig
  src/ec/packages/ec-component-page-header-standardised/README.md
  src/ec/packages/ec-component-page-header-standardised/__snapshots__/page-header-standardised.test.js.snap
  src/ec/packages/ec-component-page-header-standardised/ecl-page-header-standardised.html.twig
  src/ec/packages/ec-component-page-header-standardised/page-header-standardised.story.js
  src/ec/packages/ec-component-page-header-standardised/page-header-standardised.test.js
Labels: pr: review needed, tag: new feature

#457 feat(ecl-compliance): Page Header Harmonised, adding child template FRONT-1149
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-page-header-harmonised.html.twig
  src/ec/packages/ec-component-page-header-harmonised/README.md
  src/ec/packages/ec-component-page-header-harmonised/__snapshots__/page-header-harmonised.test.js.snap
  src/ec/packages/ec-component-page-header-harmonised/ecl-page-header-harmonised.html.twig
  src/ec/packages/ec-component-page-header-harmonised/page-header-harmonised.story.js
  src/ec/packages/ec-component-page-header-harmonised/page-header-harmonised.test.js
Labels: pr: review needed, tag: new feature

#455 feat(ecl-compliance): Page Header Core, adding child template - FRONT-1087
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-page-header-core.html.twig
  src/ec/packages/ec-component-page-header-core/README.md
  src/ec/packages/ec-component-page-header-core/__snapshots__/page-header-core.test.js.snap
  src/ec/packages/ec-component-page-header-core/ecl-page-header-core.html.twig
  src/ec/packages/ec-component-page-header-core/page-header-core.story.js
  src/ec/packages/ec-component-page-header-core/page-header-core.test.js
Labels: pr: review needed, tag: new feature

#454 feat(ecl-compliance): Site Header Harmonised, adding child template - FRONT-1092
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-site-header-harmonised.html.twig
  src/ec/packages/ec-component-site-header-harmonised/README.md
  src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
  src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js
  src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.test.js
Labels: pr: review needed, tag: new feature

#459 feat(ecl-compliance): Menu legacy, adding child template - FRONT-1108
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-menu-legacy.html.twig
  src/ec/packages/ec-component-menu-legacy/README.md
  src/ec/packages/ec-component-menu-legacy/__snapshots__/menu-legacy.test.js.snap
  src/ec/packages/ec-component-menu-legacy/ecl-menu-legacy.html.twig
  src/ec/packages/ec-component-menu-legacy/menu-legacy.story.js
  src/ec/packages/ec-component-menu-legacy/menu-legacy.test.js
Labels: pr: under review, tag: new feature

#460 feat(ecl-compliance): Site Header (deprecated), adding knobs and child template - FRONT-1089
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-site-header.html.twig
  src/ec/packages/ec-component-site-header/README.md
  src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
  src/ec/packages/ec-component-site-header/ecl-site-header.html.twig
  src/ec/packages/ec-component-site-header/site-header.story.js
  src/ec/packages/ec-component-site-header/site-header.test.js
  utils/story-utils/src/index.js
Labels: tag: new feature

#461 feat(ecl-compliance): Dropdwon legacy, adding knobs and child template - FRONT-1102
  src/ec/packages/ec-component-dropdown-legacy/README.md
  src/ec/packages/ec-component-dropdown-legacy/__snapshots__/dropdown-legacy.test.js.snap
  src/ec/packages/ec-component-dropdown-legacy/demo/data.js
  src/ec/packages/ec-component-dropdown-legacy/dropdown-legacy.story.js
  src/ec/packages/ec-component-dropdown-legacy/dropdown-legacy.test.js
  src/ec/packages/ec-component-dropdown-legacy/ecl-dropdown-legacy.html.twig
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-dropdown-legacy.html.twig
Labels: pr: under review, tag: new feature

#462 feat(footer-core): Adding child template, FRONT-1083
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-footer-core.html.twig
  src/ec/packages/ec-component-footer-core/__snapshots__/footer-core.test.js.snap
  src/ec/packages/ec-component-footer-core/ecl-footer-core.html.twig
  src/ec/packages/ec-component-footer-core/footer-core.story.js
  src/ec/packages/ec-component-footer-core/footer-core.test.js
Labels: pr: under review, tag: new feature

#463 feat(ecl-compliance): Footer standardised, adding child template - FRONT-1084
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-footer-standardised.html.twig
  src/ec/packages/ec-component-footer-standardised/README.md
  src/ec/packages/ec-component-footer-standardised/__snapshots__/footer-standardised.test.js.snap
  src/ec/packages/ec-component-footer-standardised/adapter.js
  src/ec/packages/ec-component-footer-standardised/ecl-footer-standardised.html.twig
  src/ec/packages/ec-component-footer-standardised/footer-standardised.story.js
  src/ec/packages/ec-component-footer-standardised/footer-standardised.test.js
Labels: tag: new feature

#464 feat(ecl-compliance): Footer Harmonised, adding child template - FRONT-1085
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-footer-harmonised.html.twig
  src/ec/packages/ec-component-footer-harmonised/README.md
  src/ec/packages/ec-component-footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
  src/ec/packages/ec-component-footer-harmonised/adapter.js
  src/ec/packages/ec-component-footer-harmonised/ecl-footer-harmonised.html.twig
  src/ec/packages/ec-component-footer-harmonised/footer-harmonised.story.js
  src/ec/packages/ec-component-footer-harmonised/footer-harmonised.test.js
Labels: tag: new feature

#458 feat(ecl-compliance): Menu, adding child template - FRONT-1101
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-menu-item.html.twig
  src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-menu.html.twig
  src/ec/packages/ec-component-menu/README.md
  src/ec/packages/ec-component-menu/__snapshots__/menu.test.js.snap
  src/ec/packages/ec-component-menu/ecl-menu-item.html.twig
  src/ec/packages/ec-component-menu/ecl-menu.html.twig
  src/ec/packages/ec-component-menu/menu.story.js
  src/ec/packages/ec-component-menu/menu.test.js
Labels: tag: new feature
