Repository ec-europa/ecl-twig, pull requests merged in 2020-11, with the labels that each got.

#581 chore(ECL): Upgrading ECL resources to 2.35.0 - FRONT-1820
  .nvmrc
  src/ec/storybook/.storybook/preview-head.html
  src/eu/storybook/.storybook/preview-head.html
  yarn.lock
Labels: tag: internal

#583 chore(deps): overall updates, including storybook - FRONT-1821
  package.json
  php/ec/package.json
  php/eu/package.json
  src/ec/storybook/package.json
  src/eu/storybook/package.json
  utils/ecl-diff/package.json
  utils/storybook-addon-code/package.json
  utils/storybook-addon-diff/package.json
  utils/storybook-addon-ecl-diff/package.json
  utils/storybook-addon-jscode/package.json
  utils/storybook-addon-notes/package.json
  yarn.lock
Labels: tag: internal

#582 feat(page-headers): Meta is uppercased in CSS - front-1819
  src/ec/packages/ec-component-page-header-core/__snapshots__/page-header-core.test.js.snap
  src/ec/packages/ec-component-page-header-core/adapter.js
  src/ec/packages/ec-component-page-header-core/ecl-page-header-core.html.twig
  src/ec/packages/ec-component-page-header-core/package.json
  src/ec/packages/ec-component-page-header-harmonised/__snapshots__/page-header-harmonised.test.js.snap
  src/ec/packages/ec-component-page-header-harmonised/adapter.js
  src/ec/packages/ec-component-page-header-harmonised/ecl-page-header-harmonised.html.twig
  src/ec/packages/ec-component-page-header-harmonised/package.json
  src/ec/packages/ec-component-page-header-standardised/__snapshots__/page-header-standardised.test.js.snap
  src/ec/packages/ec-component-page-header-standardised/adapter.js
  src/ec/packages/ec-component-page-header-standardised/ecl-page-header-standardised.html.twig
  src/ec/packages/ec-component-page-header-standardised/package.json
  yarn.lock
Labels: pr: under review, tag: enhancement

#585 feat(menu): Adding span for accessibiltiy - FRONT-1818
  src/ec/packages/ec-component-menu/README.md
  src/ec/packages/ec-component-menu/__snapshots__/menu.test.js.snap
  src/ec/packages/ec-component-menu/adapter.js
  src/ec/packages/ec-component-menu/ecl-menu-item.html.twig
  src/ec/packages/ec-component-menu/package.json
  yarn.lock
Labels: pr: review needed, tag: enhancement

#584 feat(gallery): Add support for external video iframe - FRONT-1817
  src/ec/packages/ec-component-gallery/README.md
  src/ec/packages/ec-component-gallery/__snapshots__/gallery.test.js.snap
  src/ec/packages/ec-component-gallery/adapter.js
  src/ec/packages/ec-component-gallery/ecl-gallery-item.html.twig
  src/ec/packages/ec-component-gallery/ecl-gallery.html.twig
  src/ec/packages/ec-component-gallery/gallery.test.js
  src/ec/packages/ec-component-gallery/package.json
  src/ec/packages/ec-components/package.json
  yarn.lock
Labels: tag: enhancement
